### ISSUE TITLE
MacOs native build

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#100]
We should add a github workflow for building mac binaries natively.

Maybe related to the cmake switch: #82

----
Fahim Dalvi dug into the macbuild part and managed to produce a .so with the following changes to the makefile:

```diff
diff --git a/client/mumble-plugin/makefile b/client/mumble-plugin/makefile
index f75e88d..9bc27d2 100644
--- a/client/mumble-plugin/makefile
+++ b/client/mumble-plugin/makefile
@@ -1,9 +1,10 @@
 .PHONY : all all-debug plugin libs test tools clean clean-all debug-on
-CC=g++
+CC=g++-10
 DEBUG=
 THREADS_UNIX=-pthread
 THREADS_WIN=-Wl,-Bstatic -lstdc++ -lpthread -lws2_32
-override CFLAGS+=-O3 -I. -I./lib $(DEBUG)
+override CFLAGS+=-O3 -I. -I./lib -I/usr/local/Cellar/openssl@1.1/1.1.1i/include/ -L/usr/local/Cellar/openssl@1.1/1.1.1i/lib/ -pthread -std=c++11 $(DEBUG)
 override CFLAGS_WIN+=-static-libgcc -static-libstdc++ $(CFLAGS) -I./lib/openssl/include/
 SSLFLAGS+=-lssl -lcrypto -DSSLFLAGS
 SSLFLAGS_WIN+=-L./lib/openssl/ -static -lssl -lcrypto -DSSLFLAGS -lws2_32 -lcrypt32
```

With additional info:
> Actually g++ on macOS is aliased to clang, and trying to compile with clang leads to the following error in multiple files (there might be more if I fix these):
> `error: no member named 'setlocale' in namespace 'std'; did you mean simply 'setlocale'?`
> This might just be a difference of g++ vs clang libs, though I'm not 100% sure. g++-10 is actually gcc (installed through a 3rd party package manager on macOS called brew)

> OpenSSL is not installed on macOS anymore for a few years now, so the way devs usually use it is install it using brew, but because of security policies, brew cannot install libraries/headers to the default directories, hence the need to specify them explicitly. There might be a better way to do it, but I didn't have much time and really wanted to see if I could just compile the plugin!

**Comment by mill-j** [comment]
I had a similar problem porting an app to mac. I need to see what I did to get it to work. I know that the gcc that ships with the Apple dev tools is very old and I needed to use clang. The namespace on mac is weird.

**Comment by dextercai** [comment]
Good news.
The makefile works well on Windows. Just need use `x86_64-w64-mingw32-g++` instead of `x86_64-w64-mingw32-g++-posix`.

I used cygwin64 with mingw32.

**Comment by hbeni** [comment]
Ready :)
Can you please test the plugin `fgcom-mumble-macOS.so`:
- [fgcom-mumble-client-0.12.0.zip](https://github.com/hbeni/fgcom-mumble/files/6349654/fgcom-mumble-client-0.12.0.zip)
- [fgcom-mumble-client-binOnly-0.12.0.zip](https://github.com/hbeni/fgcom-mumble/files/6349657/fgcom-mumble-client-binOnly-0.12.0.zip)

(both should be installable from mumbles plugin/install button)

**Comment by fdalvi** [comment]
Hi Benedikt,

I got a chance to test this; a few more macOS troubles (though not sure what you can do about them, and there are workarounds).

All executable code on macOS is placed into "quarantine" if its downloaded from some website etc without a developer having signed and notarized it. One of these things requires paying apple, one of them is free, and I'm not sure if only one is enough or you need to do both. As for a workaround, one can run the following from the terminal:

```bash
xattr -dr com.apple.quarantine fgcom-mumble-macOS.so
```

I suspect this has to be done with every update unfortunately, so it is a bit of a hindrance, but workable. Just for completeness sake, if someone does not do this and tries to install the plugin, they are met with the following dialog:

<img width="270" alt="Screen Shot 2021-04-24 at 2 04 47 PM" src="https://user-images.githubusercontent.com/859719/115956937-563b9980-a508-11eb-84c3-939e9d66f22d.png">

After doing the above workaround, I'm able to install the plugin, and see all the UDP connected messages from FG, and also see myself on the status page. However, the echo test didn't seem to work. I tried using my self-compiled version and the echo test didn't work there either, so I do not think this is a plugin issue (maybe server side issue?).

I also cant get the keyboard binding for push-to-talk to work, but this is an issue for upstream mumble :)

I think you can go ahead with the release with the above caveat (or try the echo test and if it works for you, I can try it again soon).

Best,
Fahim

**Comment by hbeni** [comment]
Hi, thanks for testing!
I indeed think that the echotest is a server side thing, have to investigate.

Thank you also for the signing line; i added it to the build chain.
Can you please try the following build: https://github.com/hbeni/fgcom-mumble/suites/2574415543/artifacts/56124998

**Comment by fdalvi** [comment]
Apologies if I was not clear, but that line is not actually signing the *.so, but telling macOS that it should be removed from _quarantine_. 

It is a choice that every macOS end user has to make, i.e. it is run after the download happens and has no effect of being added in the build chain.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hbeni** [comment]
Ah okay - then i think i cannot do anything about the warning 😢

**Comment by fdalvi** [comment]
Correct, all we can do is add that line to the instructions in the release.

Best,
Fahim

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hbeni** [comment]
> I indeed think that the echotest is a server side thing, have to investigate.

@fdalvi I restarted the services, it should work again now
