### ISSUE TITLE
Need help installing on Fedora 33 

### ISSUE THREAD

**Issue by bitwisetech** [hbeni/fgcom-mumble#104]
Hi   I have: 

 Downloaded the zip file to a temp place,  unzipped it.
 
 opened mumble, Fedora package is 1.3.4,  barely two months old, unable to find "Install" button in plugins configuration. 

 Tried mumble with path of fgcom-mumble zipfile as argument: Mumble declares "Not a configuration File" 

  Looked for the .so file specified as the library file for Linux, it does not appear to be in the package unzupped

 Tried running make clean; make in the top level the last of the consol log reads: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
# Build server components release
mkdir fgcom-mumble-server-0.12.0
mkdir fgcom-mumble-server-0.12.0/recordings
cp LICENSE server/recordings/readme.md server/recordings/fgcom.rec.testsample.fgcs fgcom-mumble-server-0.12.0/recordings
head -n 1 server/Readme.server.md > fgcom-mumble-server-0.12.0/README.md
tail +2 server/Readme.server.md >> fgcom-mumble-server-0.12.0/README.md
tail: cannot open '+2' for reading: No such file or directory
make: *** [makefile:23: release-server] Error 1

Am I out of luck, needing a release 1.4.0 that is less than two months old and that Mumble doesn't release for Linux platforms ?  Thanks

**Comment by mill-j** [comment]
Yes you need an unreleased mumble 1.4.0. Did you check the wiki for instructions on building it? https://github.com/hbeni/fgcom-mumble/wiki/Compiling-mumble-1.4.0-on-a-debian-testing-(bullseye)-system

**Comment by bitwisetech** [comment]
Thanks, that's Debian, dnf based systems must be their cornbread.  I'm not inclined to get into experimenting with alternative packages for this and running make doesn't give any indication of what's missing.

**Comment by hbeni** [comment]
The Mumble project also has an nightly built appimage, maybe it runs on your machine...
If not, and self compiling is no option, you’ll have to wait for the 1.4.0 release.
