### ISSUE TITLE
Bug: FlightGear UFO not working on MacOS

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#105]
@fdalvi I have split a new issue in order not to clogg down the mumble issue https://github.com/mumble-voip/mumble/issues/4946#issuecomment-829105634

-----
> > Just tested: works as designed. You were in the `fgcom-mumble` channel, weren't you (thats important, the plugin and also the bots are not active outside it)?
> 
> Yes, I was in the channel and tuned my (ufo) radio to 910 as well. I see myself on the status page as well.
> 
> Not sure what else could be the issue here then, maybe we can try together at some point to make sure the bot is not the issue?

The bot is not the issue, it worked with the radioGUI. To test, you can either use another plane or use the java radioGUI.
Maybe there is an issue with the UFO?
We expect a PTT=1 command in  the protocol when you push `space` in flightgear.
This also should make your mumble icon go blue, showing you are saying something.

When you use the debug build, can you please run mumble from a terminal and then look trough the output? The plugin writes what it sees and what it does; specifically we need to figure out what gets sent to the plugin from flightgear when you hit `space`.
Using mumbles built in PTT global key is _not_ enough, as this does not activate the radio! You must use flightgears PTT binding.

**Comment by hbeni** [comment]
This is what I just got from your client (and it looks perfectly good!)

It looks like you are not setting PTT for the plugin.

```
---------REMOTE STATE-----------
[mumid=41; iid=0] Fahim: location: LAT=47.259357 LON=11.354294 ALT=102.109245
[mumid=41; iid=0] Fahim: clientHostPort=:21892
[mumid=41; iid=0] Fahim: lastUpdate=12:23:32
[mumid=41; iid=0] Fahim: lastNotify=01:00:00
[mumid=41; iid=0] Fahim: 2 radios registered
  Radio 0:   frequency='910.0000'
  Radio 0:   dialedFRQ='910'
  Radio 0:    operable='1'
  Radio 0:         ptt='0'
  Radio 0:         pwr='10.000000'
  Radio 0:    operable='1'
  Radio 1:   frequency='128.3000'
  Radio 1:   dialedFRQ='128.3'
  Radio 1:    operable='1'
  Radio 1:         ptt='0'
  Radio 1:         pwr='10.000000'
  Radio 1:    operable='1'
--------------------------------
```

**Comment by hbeni** [comment]
This is what i get when you speak; it confirms what i suspected above: PTT is not active. You are virtually just talkint to the microphone but do not press the "virtual" PTT key of the radio, hence the radio does not transmit.

This is either an issue with the UFO or with the FGFS version in MacOS.
Normally this should work trough standard FGCOM-bindings without anything to be adjusted in mumble or FGFS.

```
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched(): plugin active=1; isSpeech=1
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():   plugin active+speech detected from id=41
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():   sender callsign=Fahim
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():   sender registered rmt-radios: 2
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():   check remote radio #0
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():    frequency='128.3000'
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():    ptt='0'
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():    txpwr='10.000000'
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():     remote PTT OFF
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():   check remote radio #1
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():    frequency='128.3000'
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():    ptt='0'
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():    txpwr='10.000000'
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():     remote PTT OFF
FGCom [2021-04-29 12:26:49.204]: [DBG] mumble_onAudioSourceFetched():   no connection, bestSignalStrength=-1.000000
```

**Comment by hbeni** [comment]
Resolved, issue was: UFO reassigns `SPACE` button to something else.

**Comment by hbeni** [comment]
Just added some comment for this to the troubleshooting section of the readme, and will enhance the fgfs wiki with the ufo info

**Comment by fdalvi** [comment]
Yep, looks clearer now. Thanks!
