### ISSUE TITLE
Bug: playback bot stops to replay samples after a while

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#106]
**Describe the bug**
The lua [playback-bot](https://github.com/hbeni/fgcom-mumble/blob/master/server/fgcom-radio-playback.bot.lua) does stop after a while to transmit samples over the wire.

This manifests itself for a listening client that the sending bot just goes silent, as if he wouldn't say something anymore.
It also stops in the middle of the sample. The samples do not come back to life even when restarting the listening mumble client, and the fgcom-mumble plugin can also be ruled out because it even happens with a client without plugin loaded.

From the log of the bot, nothing can be seen; specifically it still says that it had handed over the samples to the lua mumble api.
The following excerpt is from the moment the last samples are transmitted and then looping over to reread the samples again and starting to sending them in the loop; indicating all is still OK (it already is not):
```
playback timer: tick
voiceBuffer is still filled, samples: 3
transmit next sample
  eos=false
  cdc=4
  dta=160
transmit ok
playback timer: tick
voiceBuffer is still filled, samples: 2
transmit next sample
  eos=false
  cdc=4
  dta=160
transmit ok
playback timer: tick
voiceBuffer is still filled, samples: 1
transmit next sample
  eos=true
  cdc=4
  dta=160
transmit ok
no samples left, playback complete
playback timer: tick
Looped timer: update voice buffer from file
update from file successful
./recordings/fgcom.rec.ZZZZ-123.4500.fgcs: FGCS file still valid for 6939s: looping over.
```

@bkacjios I suspect maybe something is overflowing in the lua-mumble module?
@krzmbrzl Are there any server side limits on sending? Any idea how I can further debug this?

**Comment by Krzmbrzl** [comment]
> Are there any server side limits on sending? Any idea how I can further debug this?

You mean in terms of audio sending? The only limit is a "bandwidth" limit but I never encountered anyone hitting that (unless you have a weirdly configured server). To rule this out you can either increase the bandwidth setting in the server's configuration and/or transmit the audio in lower quality. If that fixes the issue, then you are indeed hitting the bandwidth limit.

**Comment by hbeni** [comment]
I meant in terms of timelimits for mic-spamming/always-sending bots...
The bandwith should not be it, because it works initially and then stops after a while. That's with no change in connected clients. It's also a real internet server attached with 100MBit, so bandwith is no issue.

**Comment by Krzmbrzl** [comment]
No audio transmissions are not rate-limited. Only the act of muting and unmuting is.

**Comment by hbeni** [comment]
Thank you! then this is something else...

**Comment by hbeni** [comment]
Ah i already reported this some time ago: bkacjios/lua-mumble#19

**Comment by hbeni** [comment]
OK, to rule out a problem with how I process my raw PCM samples, I added the feature to play OGG files to my playback bot: 2dfdd7a257c6

In essence, the bot sets up a timer which continuously checks if the ogg still plays. If not, it (re)starts playback of the ogg.

I have the same issue there, so i think it is somehow related to the timers...?

**Comment by hbeni** [comment]
bkacjios/lua-mumble#19 was fixed.
The bot should now be able to play endlessly :D
