### ISSUE TITLE
suggestion: more descriptive names of downloadable assets

### ISSUE THREAD

**Issue by MariuszXC** [hbeni/fgcom-mumble#108]
What is currently distributed as fgcom-mumble-client-0.12.0.zip is in fact a fgcom-mumble-client-_plugin_.

Indeed, the first setup requirement (in README.md) states:
"- have a standard mumble client with recent plugin support (>= v1.4.0)"

Therefore, to avoid confusion among new users, I offer this suggestion to rename the asset to a less confusing name.

Regards, Marius

**Comment by hbeni** [comment]
Good idea!


**Complications:**
For future compatibility we also provide a bin-only zip, which is hardwired into the updater.

The normal zip should work too, which should be tested, so we could also revert to a single client release zip until mumbles updater API changes this to be incompatible again, which will ease the release process.
For this i think it would be cool if the plugin updater checks if there is a bin-only release published, and if not, revert to the default release zip.

**Comment by hbeni** [comment]
OTOH it is not just the plugin which is released in the package.
We also package the RadioGUI and also the Flightgear addon with it.

This looks like the naming scheme already is good enough probably, because we distinguish between the server side and the client side.

**Comment by MariuszXC** [comment]
Well, I tried to look at the naming scheme with the eyes of a new user.

File name fgcom-mumble-radioGUI-0.12.0.zip is perfectly OK - inside is a radioGUI as expected, so no confusion.

Files fgcom-*-client-*.zip contain in fact a plugin *for* a mumble client, and one of them also code integrating with Flightgear - mildly confusing imho, hence my original suggestion.

The file fgcom-mumble-server-0.12.0.zip seems to have a similar naming issue, as it contains server-side scripts and other components *for use* with an actual server, not the server itself. Perhaps a rename to *-server-side-*.zip or -server-config-) could be considered?

Honestly, these are very small issues anyway.

Regards, Marius

**Comment by hbeni** [comment]
Hm, may be another option to rename the client release just `fgcom-mumble-<version>.zip` (without the client part), as we can expect server admins to dig deeper into it and therefore know that they need to run a mumble server and the package just extends the server side?
This way, the end user can clearly see that he doesn't need the "server" part, and picks the remaining client zip.

**Comment by MariuszXC** [comment]
Sounds OK.
On a second thought, are there any plugin naming guidelines from mumble folks? I haven't found any in Pluginguide at their wiki, but maybe I wasn't looking hard enough.

**Comment by hbeni** [comment]
> are there any plugin naming guidelines from mumble folks

No, there are none. In the near future there *might* be some additional OS name hinting.

**Comment by hbeni** [comment]
Another addition could be to include the radio-GUI in the client release zip.
I always tought of the radioGUI as optional, but also i don't like too many assets to download. The readmes in my opinion elaborate extensively on what people need and how to install it.

We could rename the `client-zip` and additionally restructure the release zip to make names clearer:
- rename dir `fgfs` to `fgfs-addon`
- rename dir `plugin` to `mumble-plugin`
- add dir `radioGUI`

This way we have just two release files, clearly distinguishing between client and server side.
In this scenario, we could even easily keep the `client` on the client-side zip.

What do you think?

**Comment by hbeni** [comment]
Looks good and unambiguous I think:

![grafik](https://user-images.githubusercontent.com/13608602/116992324-1e85dc00-acd6-11eb-983f-4967bf80afdd.png)

**Comment by hbeni** [comment]
@MariuszXC Maybe you can check the latest build and especially proofread the readme instructions. I do hope i got every place that mentionend the old structure, but four eyes see more than two...
[fgcom-mumble-0.12.1.zip](https://github.com/hbeni/fgcom-mumble/files/6420497/fgcom-mumble-0.12.1.zip)

**Comment by MariuszXC** [comment]
I forked the repo and am doing some proofreading, standby...

**Comment by MariuszXC** [comment]
Pull request sent. I took the opportunity to correct spelling (I may have missed some) and slightly modify wording here and there. Feel free to disregard :)

Can not build mumble on my system because of dependency on new Cmake (I have version 3.5.1, which is way too old) so no further functional testing is possible ATM. Will look into a possibility of a container with more up to date build environment, but no promises.

**Comment by hbeni** [comment]
The project currently builds with old-busted `make` :)

I will look into your changes and then merge.

**Comment by MariuszXC** [comment]
Ah, obviously poor wording on my part.
I meant, that for functional testing one needs at least a mumble client with plugin support, and building *that* requires cmake 3.15 or later.
