### ISSUE TITLE
Bug: FG ADF receives audio regardless of ADF/ANT mode

### ISSUE THREAD

**Issue by colingeniet** [hbeni/fgcom-mumble#116]
README.md states that audio signal can only be received through an ADF if it is in ANT mode (not ADF).
However, I hear audio from mumble both in ADF and ANT mode.

Indeed, the FG addon tests for ADF mode with regards to changing the needle for RDF, but I see no test related to audio, and the mode property doesn't appear to be sent to the plugin.

Maybe the test should be added to `recalcADFVolume()`?

**Comment by hbeni** [comment]
I tought that this is handled by the FGFS `ident` prop node, which the code maps to.
I tested this with the C172p and there it worked - doesn't it anymore?

**Comment by colingeniet** [comment]
Do you mean `ident` or `ident-audible`? The ADF volume received from fgcom-mumble only depends on `volume-norm` and `ident-audible`.

**Comment by hbeni** [comment]
Ident-audible :)

**Comment by colingeniet** [comment]
From what I've tested, `ident-audible` is independent from the ADF/ANT mode (including with the C172).
And as long as `ident-audible` is true, I hear audio from fgcom-mumble in both modes.

**Comment by hbeni** [comment]
Ok: i think i just forgot to adjust the docs.
I think the adf will output anything received as long as ident is switched on.
The ANT mode just makes the direction finder work.

so code is fine, just the docs not.

**Comment by colingeniet** [comment]
Ok, that makes sense

**Comment by hbeni** [comment]
Implemented by #115

**Comment by hbeni** [comment]
Oops wrong ticket
