### ISSUE TITLE
Bug: FGFS with less than two COM radios yield two radios in the plugin

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#117]
**Describe the bug**
Using an FlightGear Aircraft with less than two COM radios registers up to two functional radios.

**To Reproduce**
- Start FGFS with the ASK21 (one radio) or the dragon (no radio)
- Start mumble with plugin
- Look at the comment: it shows the registered radios

**Expected behavior**
Only valid radios should be registered.

**Additional context**
See for possible fix idea: https://github.com/hbeni/fgcom-mumble/commit/f33bf7c0a34ce148b04f1bc4804de6ff2c0d1072#commitcomment-50984168

**Comment by hbeni** [comment]
@colingeniet is working on this 🎉

**Comment by colingeniet** [comment]
So, if I understand correctly, we want to transmit nothing (as in only empty values) for radios which are not used, so that the parser discards these values and doesn't create the radio in the first place. So:
- [ ] Make sure we don't initialize any relevant property (to a nonempty value) if the radio is not used.
- [ ] Clear (but preferably only the fgcom-mumble specific properties) any property which is initialized by FG code even for unused radios. These properties are:
  * For COM, `frequencies/selected-mhz,volume,ptt`
  * For ADF, `frequencies/selected-khz,volume-norm`

**Comment by hbeni** [comment]
I think that summarized it.

I just had another interesting idea that may be worth investigating:
When the nasal implementation translates the fgfs radio properties into a single string property containing the sending-ready udp message string, we would get full control of what is sent. The protocol file would just send a single string property.

This not only would give us the ability to not send invalid radios at all (conserve space on the wire), but also would allow us to send arbitary radios dynamically without the need to adjust the protocol file.
Available radios would get picked up automatically this way.

**Comment by colingeniet** [comment]
I noticed the properties you added to ADFs for `publish` and `rdf-enabled`. A few questions:
- `rdf-enabled` makes sense to me, as one may want to disable fgcom-mumble RDF.
- I don't get the point of `publish` for ADFs. Does `publish=0` disable things beside transmitting audio?
- What about COM radios? I think `publish` makes sense for them (more so than for ADFs). Probably not `rdf-enabled` however?

**Comment by hbeni** [comment]
> `rdf-enabled` makes sense to me, as one may want to disable fgcom-mumble RDF.

By default radios are *not* RDF enabled. This has to explicitely be turned on via that field

> I don't get the point of publish for ADFs. Does publish=0 disable things beside transmitting audio?
> What about COM radios? I think publish makes sense for them (more so than for ADFs). Probably not rdf-enabled however?

Radios do publish their data to other fgcom-mumble plugins by default. Therefore the ADFs need to turn that off, so just the local plugin sees them (in order to receive). So no need to do `publish=1` nor `rdf_enabled=0` for ordinary COMs :)

**Comment by colingeniet** [comment]
Oh I missed the point of these properties. I thought they were to allow configuration in FG, but of course they are needed in order to transmit empty values when the radio is missing...
Thanks for the clarification!

**Comment by hbeni** [comment]
In thank you for investigating and second guess it! This helps to iron out inconsistencies in the design. 😃

**Comment by colingeniet** [comment]
> When the nasal implementation translates the fgfs radio properties into a single string property containing the sending-ready udp message string, we would get full control of what is sent. The protocol file would just send a single string property.

From a recent ML discussion, I recall that the generic protocol has a 256 byte limit on a single string. I think 3 COM + 2 ADF is already over this limit (very rough estimate: 300bytes).

**Comment by hbeni** [comment]
Ah, good to know! Then leave it as be; we already have a very good status, and adding other radios seems easy enough
