### ISSUE TITLE
Wrong Mumble version in fgcom announcement on flightgear.org

### ISSUE THREAD

**Issue by Krzmbrzl** [hbeni/fgcom-mumble#120]
From the entry post at https://forum.flightgear.org/viewtopic.php?f=32&t=37644:

> it will be part of the mumble 1.14 release.

That should be 1.4.0 :)

EDIT: The wrong 1.14 version number seems to be used a few times in that post

**Comment by hbeni** [comment]
> EDIT: The wrong 1.14 version number seems to be used a few times in that post

oops you are right

**Comment by hbeni** [comment]
Corrected :)
