### ISSUE TITLE
Update to current Mumble API / updater bundles

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#123]
- [x] C Header changes, see: https://github.com/mumble-voip/mumble/pull/5095#issuecomment-853915534
- [x] Bundling also changes: https://github.com/mumble-voip/mumble/pull/5102
  - docs at https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/Bundling.md; recent proposal: https://github.com/Krzmbrzl/mumble/blob/plugin-installer-manifest/docs/dev/plugins/Bundling.md
  - <s>ongoing</s> discussion about binary package format / zip support: https://github.com/mumble-voip/mumble
  - [x] updater needs to be pointed at the `.mumble_plugin` binary distribution/discussions/5107
- [x] Implement Manifest file specs (generate in makefile, details: https://github.com/mumble-voip/mumble/pull/5117)
- [x] thereby restructure build process to have the plugin makefile just build the plugin, and have the overall makefile deal with packaging

**Comment by Krzmbrzl** [comment]
_Header changes are now merged_ :)

**Comment by hbeni** [comment]
(33141e3 in master updates to newest headers)

**Comment by hbeni** [comment]
> Bundling also changes: mumble-voip/mumble#5102
>  -  docs at https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/Bundling.md

To implement:
- makefile needs to build:
  - `fgcom-mumble_linux_x86_64.so`
  - `fgcom-mumble_win_i386.dll`
  - `fgcom-mumble_win_x86_64.dll`
  - `fgcom-mumble_macos_x86_64.dll`
- GitHub packaging actions need to be adjusted too.
  - binOnly package needs to be renamed to ...`.mumble_plugin`
- updater need to be pointed towards the `.mumble_plugin` release asset

**Comment by Krzmbrzl** [comment]
Just as an aside: The naming scheme for the libraries will be dropped in favor of a manifest file. You are of course still free to name them in this way but it won't get mandatory (even though the docs currently describes it as such)

**Comment by hbeni** [comment]
Thank you for picking up the manifest idea :)

And i think your naming choosing was good. For my case it makes it clearer for which architecture the build happened. Who knows? Maybe we get some 32bit linux build :)

**Comment by Krzmbrzl** [comment]
> Thank you for picking up the manifest idea 

Thanks for bringing that up :D 

> And i think your naming choosing was good. For my case it makes it clearer for which architecture the build happened. Who knows? Maybe we get some 32bit linux build :)

Aye - who knows :sweat_smile:

**Comment by hbeni** [comment]
I'm nearing the implementation of this.
Workflows and makefiles annoy me.

**Comment by hbeni** [comment]
Looks good now.
@Krzmbrzl can you quickly look over the produced bundle? (i had to manually add the suffix `.zip` so github comment accepts it - just strip it): [fgcom-mumble-0.14.1.mumble_plugin.zip](https://github.com/hbeni/fgcom-mumble/files/6648873/fgcom-mumble-0.14.1.mumble_plugin.zip)

**Comment by Krzmbrzl** [comment]
> Workflows and makefiles annoy me.

_cough, cough, use cmake instead, cough cough_ :D 

> can you quickly look over the produced bundle? (i had to manually add the suffix .zip so github comment accepts it - just strip it): fgcom-mumble-0.14.1.mumble_plugin.zip

The 32-bit arch is called `x86` and not `x32`. Other than that this looks good to me. Personally I would indent the contents of `bundle` by one level but that is definitely not going to affect functionality :)

**Comment by Krzmbrzl** [comment]
Just as a note: The plugin manifest implementation has now landed in Mumble's master branch

**Comment by hbeni** [comment]
Thanks for the heads up.
I think i can thus merge this here, too. The build works, and my local test on linux looks good too.

**Comment by hbeni** [comment]
Hi Fahim,
it would be cool, if you try the latest version of mumble (development master branches, each) and see if it works now.
Maybe there was something off in the branches combinations.
I do expect it to work, at least in linux here it does with a fresh install/build.

@fdalvi

**Comment by fdalvi** [comment]
Hi Beni,

I just tried with the latest of both mumble and the plugin:

Mumble: https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=4921&view=artifacts&pathAsName=false&type=publishedArtifacts
Plugin: https://github.com/hbeni/fgcom-mumble/actions/runs/938684407

Unfortunately, same error still.

**Comment by Krzmbrzl** [comment]
@fdalvi did you perform a Debug build yet to check whether the testPlugin will be loaded?

**Comment by hbeni** [comment]
I opened a new ticket to have it concise: #126
