### ISSUE TITLE
Bug: Cessna C208: no com recognized

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#125]
**Describe the bug**
The Cessna C208 describes one "old" radio in its `instrumentation.xml`
```
<comm-radio>
    <name>comm</name>
    <number>0</number>
  </comm-radio>
```
However the FGFS addon does not recognize it. Reason: the `operable` property is not there.

The question is how we deal with this - we need a halfway reliable way to detect "old" radios too - probably the `operable` prop is just set for the new radio implementation. Maybe we should report that for the fgfs core devs to fix?

The plane however does define default props for com1 and com2 in `instruments.xml`
Is this an airplane bug?

**Comment by hbeni** [comment]
Well, the Cockpit has two KC-165 units. I come to believe that the radio implementation is buggy in this plane...
:point_up: We have to retest the handling of default radios for the addon. Maybe we need to add an override so one can manually instanciate them from insim?

**Comment by mill-j** [comment]
> The question is how we deal with this - we need a halfway reliable way to detect "old" radios too - probably the operable prop is just set for the new radio implementation. Maybe we should report that for the fgfs core devs to fix?

Is there a way we can auto-detect if operable is missing, and act accourdingly?

**Comment by hbeni** [comment]
We currently use it to detect if the radio is operational, because that was the only good indicator if the COM was defined by the craft at all... Somehow it's missing with the C208 tough. I suspect this is the old 25khz radio code not initializing it, or the aircraft not defining it properly. Maybe its just set by C++ code when there is electrical fusing or something like that. We have to dig into this, but i believe its flightgear related and I'm not sure we can tackle this from the addon.

**Comment by hbeni** [comment]
Probably we can neglet this. RedGriffin also has issues:
https://wiki.flightgear.org/Red_Griffin_ATC_compatible_aircraft#Known_incompatible_aircraft

![grafik](https://user-images.githubusercontent.com/13608602/121422569-a911c900-c96f-11eb-92f1-8d7cb7693b3d.png)

**Comment by hbeni** [comment]
Reopened: maybe we can enhance the addon GUI to force-enable COM entries....
@colingeniet

**Comment by colingeniet** [comment]
I don't get this issue.
This is the same as the default values in `FGData/Aircraft/Generic/generic-instrumentation.xml`:
```
<comm-radio>
    <name>comm</name>
    <number>0</number>
  </comm-radio>
```
So either I'm missing something, or there is something more to the C208 which causes the problem.

**Comment by hbeni** [comment]
So for you, you get plausible data sent to the plugin with the C208?

**Comment by colingeniet** [comment]
On FGAddon trunk C208B, I have the problem, and the reason is very simple:
```
  <!--  <comm-radio>
    <name>comm</name>
    <number>0</number>>
  </comm-radio>

  <comm-radio>
    <name>comm</name>
    <number>1</number>
  </comm-radio>  -->
```
If there's no radio, then there's no radio :smile:

**Comment by colingeniet** [comment]
There's a weird comment before that:
```
  <!--  Users of FG 3.1 or earlier may comment out the following lines
        to prevent the spurious error message in the console.
        The below entries MUST be the last items in this file -->
```
I'm not sure what it is referring to. I doubt it is still relevant nowadays.
Either way, that's a problem to report to the C208B maintainer (hoping there is one?).

**Comment by hbeni** [comment]
Yes, but with my version it's not commented out...

**Comment by colingeniet** [comment]
If I uncomment it in the FGAddon C208B trunk version, it works just fine.
Do you have a different version?

**Comment by hbeni** [comment]
> Either way, that's a problem to report to the C208B maintainer (hoping there is one?).

The wiki entry reports it as from Hellajas Hangar, i think.
And since the RedGriffin also declares it incompatible, i'm fine with leaving this as-is (ie. wontfix).

> Do you have a different version?

I used the FGAddon version called "Cessna 208B Grand Caravan", and i'm on 2020.4.0 (next; compiled fresh some weeks ago)
![grafik](https://user-images.githubusercontent.com/13608602/121426968-76b69a80-c974-11eb-9de8-c753a1bba9fc.png)

----

I just reponed the issue, in case you are motivated to add a functionality to the insim gui dialog to force-enable selectable radio entries (this should be probably easy: we just need to grep trough the prop tree, see if some radio has set a frequency and set `operable` on our own.). This would enable us to optionally support also "incompatible" planes.

**Comment by colingeniet** [comment]
> The wiki entry reports it as from Hellajas Hangar, i think.

I think that's the C208, not the C208B.
C208B appears to be from e_pilot, and deltaecho is pushing the changes to FGAddon.
https://sourceforge.net/p/flightgear/fgaddon/HEAD/tree/trunk/Aircraft/Cessna-208B/
Contacting one of them shouldn't be an issue.

> I used the FGAddon version called "Cessna 208B Grand Caravan", and i'm on 2020.4.0 (next; compiled fresh some weeks ago)

Then I think it should have the radios commented out:
https://sourceforge.net/p/flightgear/fgaddon/HEAD/tree/trunk/Aircraft/Cessna-208B/Systems/instrumentation.xml#l113

**Comment by hbeni** [comment]
(PM'd D-ECHO)

**Comment by hbeni** [comment]
closing this now, as its no FGCom-mumble problem and is adressed at the proper place now.
