### ISSUE TITLE
Bug: Windows updater broken

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#130]
Followup on https://github.com/mumble-voip/mumble/issues/4946

> > edit: the plugin does log what it does in the updater - that should display somewhere.
> 
> Not on Windows unfortunately as Windows does not show a programs output in the terminal roll_eyes
> 
> So the infinite recursion happens when calling the `hasUpdate` function. In order to debug this more, I would require a build with debug symbols so I can step into the code.
> 
> However as it currently seems that this issue is not Mumble-related, let's continue the discussion in an issue over in your plugin's repo.
> 
> > edit2: and like said, it's the same code that works on linux here
> 
> shrug Then I guess _something_ shows platform-sepcific behavior

----
Probably related to #126

**Comment by Krzmbrzl** [comment]
Moving my reply ffrom #126 to here:

Okay debugging a crash on Windows that seemed to be very similar to the macOS one revealed that the crash is due to a Stackoverflow happening when calling the `hasUpdate` function of the plugin.

@fdalvi can you confirm that the crash does no longer happen, if you disable plugin updates in Mumble's settings (I think you'll have to first delete the library manually in order to get Mumble to start without crashing though and then reinstall it after the settings have been changed).

@hbeni could you test whether the crash happens if you comment out the code you currently have in the `mumble_hasUpdate` function and let it just return `false` hard-coded. If this still triggers the crash then the issue is most likely on Mumble's side after all. If this fixes the crash, the issue lies somewhere in the update-checking logic :eyes:

**Comment by hbeni** [comment]
> So the infinite recursion happens when calling the hasUpdate function. In order to debug this more, I would require a build with debug symbols so I can step into the code.

See github nightly here: https://github.com/hbeni/fgcom-mumble/actions/runs/955511951
-> file [https://github.com/hbeni/fgcom-mumble/suites/3041799712/artifacts/69072421](fgcom-mumble-0.14.1_bd2579e-debug )

> @hbeni could you test whether the crash happens if you comment out the code you currently have in the mumble_hasUpdate function and let it just return false hard-coded.

will do

**Comment by Krzmbrzl** [comment]
> file https://github.com/hbeni/fgcom-mumble/suites/3041799712/artifacts/69072421

Yeah I tried that one but I still was not able to step into the code :thinking: 
Are you sure the Debug symbols are embedded into the DLL and not stored separately as a .pdb file? In that case this .pdb file would also have to be contained in the zip somewhere in order to be used for debugging :eyes:

**Comment by hbeni** [comment]
> Are you sure the Debug symbols are embedded into the DLL and not stored separately as a .pdb file?

I think so:
https://github.com/hbeni/fgcom-mumble/blob/bd2579e0e94aa52bda6dabb79e588ca647c4eb1a/.github/workflows/make-release.yml#L180-L185

**Comment by Krzmbrzl** [comment]
According to [SO](https://stackoverflow.com/a/25379297/3907364) this does not do the trick. Apparently on Windows embedding the symbols is not possible, so you always need a separate .pdb file

**Comment by hbeni** [comment]
For reference, wind64 build with `DEBUG+="-g3 -Og -DDEBUG"`, bundled up (manually remove the `.zip` from the asset file name, was needed because of github ticket uploade).
[fgcom-mumble-0.14.1.mumble_plugin.zip](https://github.com/hbeni/fgcom-mumble/files/6685240/fgcom-mumble-0.14.1.mumble_plugin.zip)

Code in the updater is:
```c++
bool mumble_hasUpdate() {
    
    return true;
}
```

**Comment by Krzmbrzl** [comment]
Please make it return `false` so that the entire update-procedure is effectively disabled

**Comment by hbeni** [comment]
> According to [SO](https://stackoverflow.com/a/25379297/3907364) this does not do the trick. Apparently on Windows embedding the symbols is not possible, so you always need a separate .pdb file

Sorry, probably cannot generate a PDB: https://stackoverflow.com/questions/26568548/generate-pdb-files-with-linux-and-g

**Comment by hbeni** [comment]
Tested on win:
- `.mumble_plugin` was installable
- mumble did start and work, no crash

So indeed it looks like it's a problem in the updater code on the plugin side.
But where!? I have no idea how to debug this properly :(

**Comment by Krzmbrzl** [comment]
> I have no idea how to debug this properly :(

Build on native Windows and run it through a Debugger. Or alternatively add a bunch of log-statements that log to a file instead of stdout and try to figure things out that way. The latter is probably a lot more tedious though :thinking:

**Comment by Krzmbrzl** [comment]
I just skimmed over the updater code and you don't seem to have any loops or extra function calls in it. Therefore my assumption would be that the bug is somewhere within httplib that you are using for your HTTP requests.

Looking at the [history](https://github.com/yhirose/cpp-httplib/graphs/contributors) of that library there seems to be quite some activity on it in recent times and given your copy of the header is rather old (~10months according to GitHub), I think it might be a good idea to try and update this to the most recent version to see if that fixes the issue already.

**Comment by hbeni** [comment]
:D haha thanks for digging into this!
I definitely will try that!

**Comment by hbeni** [comment]
So, I upgraded, let's see how it's going...
[fgcom-mumble-0.14.1.mumble_plugin.zip](https://github.com/hbeni/fgcom-mumble/files/6686215/fgcom-mumble-0.14.1.mumble_plugin.zip)

**Comment by hbeni** [comment]
hm, same result.
Mumble opens, shows the server list window, then crashes.

The plugin does log to file, however:
```
FGCom [2021-06-21 11:36:11.706]: [UPDATER] fetching update information from: https://github.com/hbeni/fgcom-mumble/releases
FGCom [2021-06-21 11:36:11.881]: [DBG] Internal state is as following:
---------LOCAL STATE-----------
plugin state: inactive
---------REMOTE STATE-----------
--------------------------------

FGCom [2021-06-21 11:36:12.611]: [DBG] [UPDATER] fetch OK; resultCode=200
FGCom [2021-06-21 11:36:12.621]: [DBG] [UPDATER] fetching version information from: https://github.com/hbeni/fgcom-mumble/blob/v.0.14.0/client/mumble-plugin/fgcom-mumble.h
FGCom [2021-06-21 11:36:12.891]: [DBG] Internal state is as following:
---------LOCAL STATE-----------
plugin state: inactive
---------REMOTE STATE-----------
--------------------------------

FGCom [2021-06-21 11:36:13.091]: [DBG] [GC] LCL searching for stale local state...
FGCom [2021-06-21 11:36:13.091]: [DBG] [GC] RMT searching for stale remote state...
FGCom [2021-06-21 11:36:13.201]: [DBG] [UPDATER] fetch OK; resultCode=200
```
so at least there is a point for further investigation.

**Comment by Krzmbrzl** [comment]
Oh now that is interesting :eyes:

But that would mean that the issue seems to lie in the RegEx calls. Maybe you should add some more logs in between the different regex lines to see where exactly it breaks :thinking:

**Comment by hbeni** [comment]
I wrote a small wrapper to test the check:
```
beni@segin:~/Dokumente/FGFS/work/FGCom-mumble/client/mumble-plugin$ ./updater_test 
Test tool for FGCom updater
FGCom [2021-06-21 14:40:35.878]: [UPDATER] fetching update information from: https://github.com/hbeni/fgcom-mumble/releases
FGCom [2021-06-21 14:40:36.738]: [DBG] [UPDATER] fetch OK; resultCode=200
FGCom [2021-06-21 14:40:36.740]: [DBG] [UPDATER] fetching version information from: https://github.com/hbeni/fgcom-mumble/blob/v.0.14.0/client/mumble-plugin/fgcom-mumble.h
FGCom [2021-06-21 14:40:37.298]: [DBG] [UPDATER] fetch OK; resultCode=200
FGCom [2021-06-21 14:40:37.302]: [DBG] [UPDATER] parsed version_major=0
FGCom [2021-06-21 14:40:37.303]: [DBG] [UPDATER] parsed version_minor=14
FGCom [2021-06-21 14:40:37.303]: [DBG] [UPDATER] parsed version_patch=0
FGCom [2021-06-21 14:40:37.303]: [DBG] [UPDATER] latest version: 0.14.0
FGCom [2021-06-21 14:40:37.303]: [DBG] [UPDATER] download from:  https://github.com/hbeni/fgcom-mumble/releases/download/v.0.14.0/fgcom-mumble-0.14.0.mumble_plugin
FGCom [2021-06-21 14:40:37.303]: [DBG] [UPDATER] current=0.14.1;  compareTo=0.14.0;  isNewer=0
FGCom [2021-06-21 14:40:37.303]: [DBG] Version check: latest='0.14.0'; newer=0
FGCom [2021-06-21 14:40:37.303]: [UPDATER] Version is up to date.
Test done.
```

Let's try what it does in windows...

**Comment by hbeni** [comment]
There is definitely something missing on windows (i added a " stripping HTML..." message in front of the replacer regex):

```
E:\>updater_test.exe
Test tool for FGCom updater
FGCom [2021-06-21 12:59:45.887]: [UPDATER] fetching update information from: https://github.com/hbeni/fgcom-mumble/releases
FGCom [2021-06-21 12:59:46.341]: [DBG] [UPDATER] fetch OK; resultCode=200
FGCom [2021-06-21 12:59:46.341]: [DBG] [UPDATER] fetching version information from: https://github.com/hbeni/fgcom-mumble/blob/v.0.14.0/client/mumble-plugin/fgcom-mumble.h
FGCom [2021-06-21 12:59:46.622]: [DBG] [UPDATER] fetch OK; resultCode=200
FGCom [2021-06-21 12:59:46.622]: [DBG] [UPDATER] stripping HTML tags from response body

E:\>
```

**Comment by Krzmbrzl** [comment]
Maybe you could check whether the issue is with the regex or with accessing the message's body by splitting the two parts apart and separate them by a log message

**Comment by hbeni** [comment]
```
E:\>updater_test.exe
Test tool for FGCom updater
FGCom [2021-06-21 14:06:57.312]: [UPDATER] fetching update information from: https://github.com/hbeni/fgcom-mumble/releases
FGCom [2021-06-21 14:06:58.312]: [DBG] [UPDATER] fetch OK; resultCode=200
FGCom [2021-06-21 14:06:58.312]: [DBG] [UPDATER] fetching version information from: https://github.com/hbeni/fgcom-mumble/blob/v.0.14.0/client/mumble-plugin/fgcom-mumble.h
FGCom [2021-06-21 14:06:58.890]: [DBG] [UPDATER] fetch OK; resultCode=200
FGCom [2021-06-21 14:06:58.890]: [DBG] [UPDATER] parsed version_major=0
FGCom [2021-06-21 14:06:58.890]: [DBG] [UPDATER] parsed version_minor=14
FGCom [2021-06-21 14:06:58.890]: [DBG] [UPDATER] parsed version_patch=0
FGCom [2021-06-21 14:06:58.890]: [DBG] [UPDATER] latest version: 0.14.0
FGCom [2021-06-21 14:06:58.890]: [DBG] [UPDATER] download from:  https://github.com/hbeni/fgcom-mumble/releases/download/v.0.14.0/fgcom-mumble-0.14.0.mumble_plugin
FGCom [2021-06-21 14:06:58.890]: [DBG] [UPDATER] current=0.14.1;  compareTo=0.14.0;  isNewer=0
FGCom [2021-06-21 14:06:58.890]: [DBG] Version check: latest='0.14.0'; newer=0
FGCom [2021-06-21 14:06:58.890]: [UPDATER] Version is up to date.
Test done.

E:\>
```

And from mumble within:
```
FGCom [2021-06-21 14:07:19.039]: [LOG] Logfile opening: C:\Users\Beni\Documents\fgcom-mumble.log; result=success
FGCom [2021-06-21 14:07:19.039]: performing offline initialization
FGCom [2021-06-21 14:07:19.039]: [UDP-server] server starting
FGCom [2021-06-21 14:07:19.039]: fgcom_initPlugin(): not connected, so no online init possible (will try later)
FGCom [2021-06-21 14:07:19.039]: Initialized plugin
FGCom [2021-06-21 14:07:19.039]: [UDP-server] udp socket bind succeeded
FGCom [2021-06-21 14:07:19.039]: [UDP-server] server up and waiting for data at 127.0.0.1:16661
FGCom [2021-06-21 14:07:19.655]: [UPDATER] fetching update information from: https://github.com/hbeni/fgcom-mumble/releases
FGCom [2021-06-21 14:07:21.196]: [UPDATER] Version is up to date.
FGCom [2021-06-21 14:07:31.636]: Established server-connection with ID 0
FGCom [2021-06-21 14:07:31.646]: fgcom_initPlugin(): not connected, so no online init possible (will try later)
FGCom [2021-06-21 14:07:31.826]: Server has finished synchronizing (ServerConnection: 0)
FGCom [2021-06-21 14:07:31.826]: There are 4 users on this server. Their names are:
FGCom [2021-06-21 14:07:31.826]: 	FGCOM-Recorder
FGCom [2021-06-21 14:07:31.826]: 	FGCOM-Status
FGCom [2021-06-21 14:07:31.826]: 	Beni
FGCom [2021-06-21 14:07:31.826]: 	SE-JG
FGCom [2021-06-21 14:07:31.826]: performing online initialization
FGCom [2021-06-21 14:07:31.826]: got local clientID=5
FGCom [2021-06-21 14:07:31.826]: Server has 2 channels, looking for special ones
```

So looks fixed for me :)
Not crashing anymore :) 🎉 🙌

**Comment by hbeni** [comment]
Just so we have it in the archives here, the problem was, that `std::regex_replace(string, pattern, string)` did behave really strangely on windows. It seemed to go into an infinite loop. Maybe the problem is compiler (mingw) specific.

The solution was simply top not use `regex_replace` but enhance the pattern for the versions that they ignore the tags themselves. That makes the pattern unwieldy to read (that is what i called _ugly_ above, the code itself should be fine).

**Comment by Krzmbrzl** [comment]
Hm yeah maybe MinGW screwed that implementation up.

However if the macOS bug was the same as the Windows one, then this would mean that it's screwed in the same was as in MinGW which seems unlikely. Are you using a different compiler for macOS than you use for Linux? If so this rules out the possibility that the macOS issue is the same problem because we know the code runs on Linux :thinking: 

Was the new fix also verified to fix the issue on macOS? :eyes:

**Comment by hbeni** [comment]
> Was the new fix also verified to fix the issue on macOS?

I'm waiting for Fahim to test: https://github.com/hbeni/fgcom-mumble/issues/126#issuecomment-865091884
