### ISSUE TITLE
Feature request: Low pass filter 4Khz

### ISSUE THREAD

**Issue by VoladorUK** [hbeni/fgcom-mumble#135]
Authentic effect option for VHF frequencies for aviation communications:
according to https://en.wikipedia.org/wiki/Airband
Airband Wikipedia:

> Audio properties
> Usually, the whole transmission is contained within a 6 kHz to 8 kHz bandwidth, corresponding to an upper audio frequency of 3 kHz to 4 kHz.[16] This frequency, while low compared to the top of the human hearing range, is sufficient to convey speech. Different aircraft, control towers and other users transmit with different bandwidths and audio characteristics.

A low pass filter that caps at 4Khz would bring an authentic quality to the communications further increasing the level of experience. If there was an option checkbox or similar, users could choose or not to have the effect turned on.

**Comment by hbeni** [comment]
Thanks for the reminder!

There is already a highpass and a lowpass filter stage implemented. It is even reacting to degrading signal levels to simulate loss of information:
https://github.com/hbeni/fgcom-mumble/blob/d0ab8913155bd59670ac84fd0a85229bb5817d3b/client/mumble-plugin/lib/audio.cpp#L126-L151

When we talked about it last week, I think you said something about simulating narrower band and loss of information?

**Comment by hbeni** [comment]
Already implemented, closing with Voladors consent
