### ISSUE TITLE
FeatureRequest: mobile ui for Statuspage

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#150]
Currently the clients and recordings display alongside each other. Thats fine for desktop, but on mobile the tables break badly.

We should make the recordings tables display below the clients one on narrow screens.

- - -
- https://www.smashingmagazine.com/2018/02/media-queries-responsive-design-2018/

**Comment by mill-j** [comment]
Yup, the status page displays pretty badly under mobile platforms. If you need help testing on different size devices, I've got plenty that'd work. Of course you can always use the devtools in Firefox, usually simpler/faster than constantly pushing to a device for testing. I've done a bit of web development, but I haven't  got around to digging into the source for the status page yet.
