### ISSUE TITLE
Bug: Recording is wrong with non-default „ Audio per packet“ setting

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#152]
**Describe the bug**
The mumble client default „audio per packet“ setting is 20. This is also what is hardcoded currently in the recorder bots FGCS file header.

When the actual recorded packets speed differ from that (10 or 40, 60), the Play-back gets too slow or too fast and potentially garbled.

The solution is that the FGCS fileheader gets the actual used client speed set. However a problem emerges here:
The Fileheader is written when the file is opened. At that time we would need the speed from the mumble data packet, but this is not available right now.
To solve this right now, we would need to buffer the write of the header until we actually close the file. Until then we have time to inspect the incoming packets timing and deduce the used client setting, which then can be written to the header data before persisting it to disk.

**To Reproduce**
1. change mumbles setting to something other than default 20
2. record something with the 910 echo test
3. hear garbled voice

**Expected behavior**
Correct recording and playback regardless of the setting

----
RELATED TO https://github.com/bkacjios/lua-mumble/issues/16

**Comment by hbeni** [comment]
@bkacjios
Hi there, I remember that we talked about this already.
Do we have access to the spacing in the audio packets („audio per packet“ mumble client setting) in the incoming audio hook already?
If not: do you think that calculation out of the received timings is feasible, or how can I do this?
Is this even solvable from our end?

**Comment by bkacjios** [comment]
One thing you could do is check how much time elapsed since receiving an audio packet, then setup your timer to use that value for each packet. This way it will play back with the exact same timing that the client did.

Something along the lines of this

```lua
client:hook("OnUserSpeak", function(client, event)
	local time = mumble.getTime()
	local delay = (event.user.last_spoke or time) - time

	-- save delay for the current voice packet

	event.user.last_spoke = time
end)

local playback_timer = mumble.timer()

-- Create a timer that DOESN'T repeat and starts immediately
playback_timer:start(function(t)
	-- send the recorded voice frame
	t:set(delay) -- repeat the timer at whatever interval we saved
	t:again() -- go again
end, 0, 0)
```

**Comment by MariuszXC** [comment]
Re: buffering.
It is not strictly necessary, file seek call is useful here.
1. write a default header
2. proceed recording
3. once sampling rate is known:
a) remember current file pointer
b) fseek to header
c) overwrite header with updated values
d) fseek to position saved in step a and continue as normal.

**Comment by hbeni** [comment]
@MariuszXC very good idea!
How does this react if the byte length if the header is different? I guess it just overwrites, so I need to check if the header format currently supports space as buffer.

Maybe I can also just seek to the position if the value I want to overwrite or so.

However, writing the samples to some tmp file and then copying them over to a final file with the final header seems more safe, for just a small increase of runtime…

**Comment by MariuszXC** [comment]
In most cases sampling rate is just a binary value field inside the header, so it is a matter of overwriting a couple of bytes, but the field size does not change. The easiest approach (assuming you have an equivalent of typedef struct {...} header; ) is to simply update data in this structure and then write it again in place of the original header. Sizeof(header) will be constant.

A solution with a temporary file is fine, but costs double the disk space. Hardly a consideration nowadays  ;)

**Comment by hbeni** [comment]
No: the header format is ascii.

disk space: double only fir the duration of the copy process, and we talk a few kb per recording :)
