### ISSUE TITLE
FeatureRequest: FGFS: Intercom support for copilot module

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#164]
Flightgear has some [Co-Pilot/Pax ](https://wiki.flightgear.org/Dual_control)module where a Plane can be entered by two people.
Some planes share an intercom system (-> audio panel) where pilots can talk to each other.

It would be nice if the intercom system would be handled transparently by the user, i.e. 
* No pilot interaction needed to set this up (just have fgcom-mumble running and use the existing fgfs copilot feature)
* Basic handling for planes not providing advanced integration
* Support for cool intercom handling 
(for example the c182s/gma340 supports some interesting features to split the channels between pilot and passengers). As this is plane specific, the implementation here would need to provide some capability to do this.
* Support for PTT split
(what happens when pushing PTT, vs just talking on the intercom? How to distinguish that? PTT=1->radio; PTT=0 intercom? This would need some planning/design choices)
* Other SIM support - the feature should be FGFS agnostic in my opinion, so changes to FGCom-mumble should be in such a way that they are usable by other sims too

* Would be good to have a channel template in RadioGUI so one can join the intercom using the RadioGUI

* Supported by (needs): https://github.com/hbeni/fgcom-mumble/pull/165

----
:bulb: A current supported "hacky" intercom simulation could be made by just invoking a parallel radioGUI instance, setting um the intercom with your pal. All that is needed is a shared `PHONE:...` channel name with your copilot. If run on a dedicated device (other PC or phone etc), the radioGUI also serves a convenient  button for the intercom, out of the box

**Comment by hbeni** [comment]
From a technical perspective of the current implementation, it would be enough to create a virtual "intercom" radio by the fgfs-addon, when the copilot module is active _and_ coupled. The mutual "frequency" must be unique to the plane involved (callsign).

There currently lacks a "feature" to activate the PTT of the intercom, so we need some idea of switching that (a quick first tought is to just activate it always when no radio PTT is active, BUT the problem is that we are going hot-mic then which should be avoided -maybe some additional keybind is a good idea.)

For additional cool audio handling (in case the PHONE one is not enough) we could think about a separate radio_model in the mumble plugin which is aware of intercom characteritics.

**Comment by MariuszXC** [comment]
The xmit button would need some thought. On some airliners, there is a toggle switch on radio panel, which can either be toggled to R/T (radio transmit) or IC (intercom). But in FG we do not have such 3-way controls easily available. But we traditionally used two different buttons for radio transmit (for comm1 and comm2 separately). So one way to approach this is to assign one of these keys to intercom transmit (probably the key which had been used for comm2) and use the other key for radio transmission, with additional property rules to switch between transmitting on comm1 or comm2, probably according to audio panel configuration set by the pilot.

The "frequency" used for PHONE config would have to be determined by the copilot subsystem, probably as some combination of a plane model and main pilot callsign, and transmitted over the MP to the other instance, where a copilot role is located. The main technical requirement is, that this 'frequency name' be unique even in a use case, where many identical planes are flying together. Then the copilot subsystem could hint the fgcom plugin about the "frequency" to use for intercom in that particular copilot plane/user instance.

The other approach, as I originally envisioned, would be to use the _remote_ callsign as a frequency input to intercom radio (so user A enters 'phone frequency' B) and user B enters A. Such connection could be then automatically detected and bridged server-side, but this would require additional complexity in FGCom-Mumble.

**Comment by hbeni** [comment]
Agreed, Can we discuss the xfer button a little deeper?

For an easy start and fallback for cases where no fgcom integration of the planes audio panel has been done yet (aka: all), we could enhance the fgcom combar which is already there.

The main problem I see is that the audio Panel is a thing best modelled plane sided, because characteristics and capabilities are differently for each plane.
I don‘t think that there is a good way to provide a default here.
And positioning of the intercom radio is dependent on the actual plane too, as airliners have often more than just com1/com2.

**Comment by hbeni** [comment]
> So one way to approach this is to assign one of these keys to intercom transmit (probably the key which had been used for comm2) and use the other key for radio transmission,

Following up on this, I think the better (because: downward compatibility) way could be to assign a third keybind.
But like said above, this is a little more complex than just using COM3, because on some planes COM3 is just another normal radio. I think we agree, if we say the keybind should always transmit on the intercom, regardless how many radios are installed.

**Comment by MariuszXC** [comment]
Yes, this is the least common denominator, so to speak.

**Comment by hbeni** [comment]
Currently the Protocol file is static (ie. the transmitted radios to the mumble plugin is fixed).
Once upon a time I already started code to dynamicalize the radios, so the protocol file just transits a single "output" property which is dynamically built by a nasal code piece. This could serve the underlaying fundament to make this easy in nasal space.

https://github.com/hbeni/fgcom-mumble/tree/addon-dynamicalizeRadios

**Comment by hbeni** [comment]
Opened a PR to track this: https://github.com/hbeni/fgcom-mumble/pull/165

Discussion should move there for the dynamicalization.

**Comment by MariuszXC** [comment]
I'll try to follow on PR #165 a bit later, as time permits.

On the hot mic problem: I had a look how the Intercom works in a DA40 and was a bit surprised to find, that they use pure voice activated intercom transmission (with an activation threshold adjustable on intercom panel individually for each pilot). So, when they turn the adjustment fully open, the mics are activated by background noise, which is effectively a hot mic for intercom. Funny, but real-life. What I am trying to say is that hot mic is not always a problem, provided we can configure some radios for ptt and some for voice activation. If not, then a dedicated button for IC-PTT is perfectly fine.

On the automatic (dynamic) bridging: If it was to be implemented server-side, I think the best approach would be to leave PHONE functionality exactly as-is and introduce another 'protocol' name. The first which came to mind was AUTOPHONE ('APH' for short), but probably something nicer and shorter can be thought of. Anyway, the 'frequency' config for 'APH' would consist of a tuple: ``<Pilot-ID, {<Co-Poilot1-ID>, [<Co-Pilot2-ID>, ...] }>``, so a call sign of a local pilot and set of call signs of other pilots who create a crew of a given plane. Note that this 'frequency' is created from the local perspective of each participating pilot so would look different on each user end. For example: ``<A, {B,C}>``, ``<B, {A,C}>`` and ``<C, {B,A}>`` is valid for a crew of three users A, B and C.
This tuple would be sent to the server, where it would be decomposed into pairs: ``<Pilot-ID, Co-Pilot1-ID>``, ``<Pilot-ID, Co-Pilot2-ID>``, etc... and each pair would be entered into a global data structure 'D' (an array or a set) holding such pairs. 
A code using an observer pattern would react to any modifications of this data, in other words, a notification of addition or deletion of data from 'D' would trigger an action.

Addition of each new pair would trigger a search for a reciprocal pair, i.e. if ``<A,B>`` pair was added a search would be made for ``<B,A>``. If it was found, a virtual audio circuit would be established between the two users. If a circuit was already existing, another user would be included in it.

Deletion of a pair would cause a check whether it was a last user of a previously established audio circuit. If yes, that circuit would be destroyed. Otherwise the circuit should remain, because a user may reconnect (they may have a temporary network issue).

**Comment by hbeni** [comment]
> On the hot mic problem

That is very interesting. The problem with "voice activation" is that it will not work reliably in our scenario, because it relies on mumbles settings itself. Not every user is configuring the voice activation.
Also, there is some automatic mapping of mumbles mic-open state to fgcom-mumble radios PTT buttons, so this would break that feature.
I really would say, that introducing a new IC-PTT transmit keybind would be the best way to go.




> On the automatic (dynamic) bridging [...]

I think this is more complex than neccesary. To establish a shared intercom channel, we already have everthing in place.
* On the mumble side, we just establish a shared channel, like the radio channels work. This simulates the "availability" of the intercom, where one can plug his headset into, so to speak. The only difference is that everyone knowing the channel name can hop into it, but that is really an underlaing mumble "problem", because we use that as infrastructure and thus every security measure we want to "fix" here is escapeable on the mumble layer.
* And on the fgfs-addon side, we calculate the intercom channel, and make it unique to the participants.
* That means, that someone can use a radioGUI to connect to the intercom, or any other client supporting the protocol. That is a feature, not a bug in my opinion, and it enables other sims to use the feature too like msfs)
* Everything on the infrastructure side remains on the mumble layer (like connection failures etc) and reconnecting is a breeze (just hop into the mumble channel again, or let mumble reconnect automatically)

**Comment by hbeni** [comment]
All of that is already there: Just everyone needs to tune the "IC radio" to Frequency `IC:D-EBHX:crew`. Everything then works as described. There is no need for a "handshake" procedure like described above. You can even test that already with the radioGUI with the current FGCom-mumble release.
All that is needed is that the FGCom-Mumble FGFS addon establishes a "virtual IC radio" that can be further tuned by the plane developer, so there is an actual virtual radio to tune the special frequency to (which is done in the backend by the addon automatically, and *that* is where we need some more code)

**Comment by MariuszXC** [comment]
> Just everyone needs to tune the "IC radio" to Frequency `IC:D-EBHX:crew`.

And that is the step I was thinking how to automate. On a human level I'd rather say who my peers (fellows) are, than deal with channel names.

>With FGCom-mumble all users are in one physical mumble channel. the plugin does the grouping and for the IC-frequency prefix we can easily add a constraint to cut signals...

Then the group membership (i.e. A, B and C mutually declaring willingness to form a group) is a perfect signal cutoff metric. Not a member? No signal for you. :)

**Comment by hbeni** [comment]
I envision it like this:

- user starts fgcom-mumble as usual
- user starts fgfs
- user press the IC button and intercom works

Under the hood, the fgfs-addon adds a "virtual IC radio" with the dynamic frequency tuned, based on the information provided by the copilot module (that is: only do that when there is a connection to a pilot/copilot and from that we can deduce the callsign we need for building the dynamic frequency).
I did not look into the technical details of the copilot module, but  think the information needed should already be queryable.

**Comment by hbeni** [comment]
I have a first draft local here, still needs some tuning.

Three things are issues right now:

1. The Combar code is rather fixed and i have no good idea yet how i can dynamically create the additional buttons. I would like to show the IC button only when there is actually IC functionality, as most of the time there will be no IC.
2. The code to detect an established copilot connection is yet to be done. This is not as easy as it looks, because of lacking properties. Still searching.
3. There seems to be a size limit for a `getValue()` call. Currently, COM4's UDP code will be truncated, despite beeing there in the property. I think I remember that i already encountered that problem while testing a prior version of the FGFS addon, but I'm not sure what the clue was - I think it was some limit in C code. Maybe we need to add some kind of multiplexer or so, to write COM1-3 to one out property, COM4-6 to another, both transmitted in the protocol file.
