### ISSUE TITLE
Support 8.3 channel spacing overlap 25khz

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#33]
(Followup on #28; see also: https://833radio.com/news/show/7)

Currently any frequency is supported. The plugin expects all clients to agree on a shared notion of „frequency“ however.

The radio model should however be adjusted, so slightly misaligned frequencies can be received, as could be the case with some 25khz and newer 8.3 frequencies.

----
From mickybadia at https://github.com/hbeni/fgcom-mumble/issues/28#issuecomment-665645690
> However note that now, you have to assume everybody with an 8.33 spacing, the way to test if two freq's (in MHz) are in tune being: abs(frq1 - frq2) < .025 / 3 / 2. Also see comment [*] below.
> 
> Good test values to combine are:
> 
>     122.00 (traditional freq)
>     122.005 (8.33 name for the same frequency as above; both should be in tune; real freq is not the closest 8.33 freq)
>     122.010 (distinct 8.33 channel whose real freq is not the closest 25-spaced freq; in real life though, ACFT with older radios might hear it, slightly out of tune; do you want to simulate that? follow-up comment [*] below)
>     record an ATIS on an 8.33 channel (e.g. the new 132.980 at EHAM); see if a flight sim cockpit can still hear it with an old radio (displaying 132.97)
> 
> [*] I think I might add a ticket for that because it is a new feature, still not discussed, but definitely part of real life and quite easy to simulate. The problem is that with real freq values only and with the current info from the clients, you have no way of accounting for the coexisting radio generations ("8.33" vs. older) in the airspace. You cannot know if a radio has a 25 or an 8.33 kHz freq spacing for its tuning. So for real simulation, perhaps a COMn_833=0/1 field would be advised, defaulting to 0 to allow the legacy FGCom integration to work. Then you would be able to adjust the "in-tune" test to know if a radio picks up a signal or not, and even the signal quality :-)

**Comment by mickybadia** [comment]
I think you said you had found a way of telling whether FG ACFT were 8.33-capable (looking up two properties). If this is correct, one option for this issue could be to just assume that everybody is 8.33 unless you get a hint otherwise.
But I think this will break with OpenRadar... Do you want to receive a COMn_833=1 for the capable radios to allow for this?

**Comment by hbeni** [comment]
Sorry, not sure yet. I digged around in FGFS and found a property that sets it in the aircraft xml, yet it seems not to be exposed to the property tree.

But anyway, i would suppose something like COMn_MOD (for "mode") or COMn_TYP (for "type") would be more suited, because it allows for different types in the future. It may just be not that easy to get out of FGFS, so another core change (albeit a small one) is on the horizon...

**Comment by hbeni** [comment]
Notice: This is prepared and partially implemented with PR #36 (for Issue #34).
For the matter of the implementation, basic overlap is realized, eg. tuning to 25kHz 118.25 will be able to receive the 8.33 channel 118.030 (but not 118.035). The formula is still rather crude, as i have no good idea of radio wave physics.
From a gamers perspective, it should be "good enough" already, i think.
Testing still pending.

**Comment by hbeni** [comment]
Was merged by #36
