### ISSUE TITLE
Proper frequency behaviour

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#34]
@mickybadia and I just had a talk about the 25/8.33 frequency stuff and i just want to note down briefly what i had taken from it.

We just had a talk about the 25/8.33 frequency stuff and i just want to note down briefly what i had taken from it.

This is a raw reminder for me, so i probably need some time to digest the links and info provided.

Infos:
- Link describing the frequency/channel scheme: https://833radio.com/news/show/7
- Code from ATC-Pie may help to peek: base/comms.py
- ATC-Pie commit 9bb529ba is ready for testing the changes

Needed changes:
- [x] Documentation should state that "carrier wave frequency" is the basic expected format for COM_FRQ fields.
- [x] Documentation for COM_FRQ fields must state that the frequency is converted if its recognized as 25/8.33kHz channel name internally (FGCom compatibility).
- [x] We need to change the frequency handling in the COMn_FRQ fields:
  - if non-numerical: use as-is
     - except for `RECORD_<tgtFrq>` -> needs to convert too, so replay will happen on the correct real frequency
  - if more significant than 3.4: treat as "real frequency" -> use as-is (ATC-Pie will use this)
  - if numerical but with lower precision: see if it is a channel name in the 25khz or 8.33 scheme; if yes, convert to real frequency (see table in link)
- [x] the frequency equality check need to be changed too: either just compare by precision of 3 decimals (properly rounded, see table) or do it by a bell courve that lowers signal quality when off (depending on radio type; which will help us later for the 25khz radio simulation, see #33)
- [x] RDF output will change (automatically, code is already in place) to the real frequency
- [x] Investigate flightgear if we can get out the real frequency via a property somewhere. It is surely already there somewhere...
  - [x] adjust fgfs protocol file so 25kHz and 8.33kHz is handled correctly

In essence, we get an proper actual real frequency internally that can serve as base for future simulations. Mikey stated truly, that this is the only unambiguous identifier we should use. A strong argument was, that the officials may change the channel naming scheme in the future. With the changes outlined above, we then just need to introduce new conversion rules; or even better, do nothing, because all clients already supply >= 4 decimals (aka real frequencies) 

----
Tests:
- [x] ATIS recording on new 8.33 channel still working
- [x] ATIS recording on 25kHz still working
- [x] ATIS replay on 8.33 working
- [x] RDF output gives real wave frequency
- [x] 910.00 echo test still working
- [x] ATC-Pie and c172 can communicate on 25kHz and 8.33kHz
- [x] 25kHz and 8.33 basechannel tuning is receivable (overlap test for #33: 122.00<>122.005 working good; 122.00<>122.010 not simulated yet, that will come in #38)

**Comment by hbeni** [comment]
I have read trough the links you gave me and also the FGFS mailing list for it's radio implementation: https://sourceforge.net/p/flightgear/mailman/message/34151391/

- FGFS radios can be switched to 8.33 mode by the aircraft.xml
- If they are switched, an *extra property* pops up, yielding the proper real frequency (`selected-real-frequency-mhz`).
- The problem with FGFS protocol files is, that i cannot "switch" depending on some setting. I can just submit both properties (the new one and the old one (which should probably be switched to `selected-mhz-fmt`also, because its always 6 digits)).

But we can make it really simple now:
- make the changes outlined above to change to real-frequency
- The FGFS fgcom-mumble protocol file will be enhanced to always transmit two `FRQ` values: the first one is the legacy 25khz property, and the second occurence contains the real frequency from the 8.33 implementation; this will overwrite the old value if both are given; yielding the real frequency in this case.
Future changes to this likely will give new properties (i think) so we can just enhance the fgfs protocol file again and be ok

**Comment by mickybadia** [comment]
OK I am updating my impl. to ensure .4 precision in the freq values sent (excluding the special echo test one, which is not a real freq anyway, in case a fixed "910.000" is what you want).
As for the rest, it mostly depends on what you _can_ do from FG. I don't think it will affect your interface with the ATC clients so I will trust your judgement. The only thing is: given the goal of ticket #33, you will need to know which radio is 8.33-capable, and you cannot tell for me with what I send you. So I will have to change sth to account for that (fu2 #33).

**Comment by hbeni** [comment]
> in case a fixed "910.000" is what you want

It's already implemented so that  everything in the range from "910" to "910.<arbitary number of zeroes>" will be recognized.

> you will need to know which radio is 8.33-capable

Yes, that will probably be the case.... i have no solution yet, but let's tackle that down the road. With the changes made here, we at least have the option to implement that... somehow... probably just another `COM_`... field that can be mapped?

**Comment by hbeni** [comment]
@mickybadia so, i think i did it. Good that i have holidays, so i could spend all sunshine days coding :smiling_imp: 

I made a small test tool, that vizualizes the conversion; output attached.
Can you please skim over it if i got something wrong (the limited list from the website you gave me seems to match)?
[25kHz_833kHz-testresults.tar.gz](https://github.com/hbeni/fgcom-mumble/files/5004043/25kHz_833kHz-testresults.tar.gz)

**Comment by mickybadia** [comment]
The old freq. system looked fine.
However, although probably without consequences because this seems only to be a presentation thing, the 8.33 list has something weird: each 100kHz range should be divided in 12 entries (vs. 4 in the old scheme), whereas you show 15. What happens is that you included 3 of the old scheme in your list (i.e. 25, 50 and 75 endings), but then why not 00?

**Comment by hbeni** [comment]
Too much wine 😅😇
The lists do not represent the available channels or frequencies, but an sample from conversion attemps (i could generate a list in .001 stepping too)

I loop through the values with a shell script and probably got something wrong there.
But it’s a good thing, because it shows the converter is working.

**Comment by hbeni** [comment]
Added the testcase, now still looking good!

```
"8.33kHz";"real"
"127.600";"127.6000"
"127.800";"127.8000"
"127.900";"127.9000"
"128.000";"128.0000"
"128.100";"128.1000"
"128.300";"128.3000"
"128.400";"128.4000"
"128.500";"128.5000"
"128.600";"128.6000"
"128.800";"128.8000"
"128.900";"128.9000"
"129.000";"129.0000"
"129.100";"129.1000"
```

Ok, i still have some tests missing on my paper strip, maybe i have time this evening to conduct them.
But i think, we are close to finishing this :) :+1:

**Comment by hbeni** [comment]
I found something "off", passing the two COMn_FRQ values from flightgear results in always notifying the remotes.
The reason is the float stuff: the conversion yields a slightly different value than the transmitted "real" field:
```
FGCom: [DBG] [UDP] conversion result to realFreq=120.90834
FGCom: [DBG] [UDP] Segment='COM2_FRQ=120.90833'
FGCom: [DBG] [UDP] Parsing token: COM2_FRQ=120.90833
FGCom: [DBG] [UDP] detected real wave frequency format=120.90833
```

**Comment by hbeni** [comment]
@mickybadia i checked RDF positively:
- plugin sends real frequency now
- RDF signal is received and displayed correctly

**Comment by hbeni** [comment]
There seems to be something wrong with the ATIS stuff.
910.00 test does still work, so the recorder bot basicly *does* work.

**Comment by hbeni** [comment]
ATIS tested OK!

the only thing left is that the botmanager spawns a new playback bot for each recording.
- [ ] instead, the botmanager must check that there is not currently an ATIS bot playing for the callsign at that frequency and only spawn one, if there is no bot instance yet.
  (The running playback bot picks up the refreshed sample automatically already)

**Comment by hbeni** [comment]
Finally tested OK, so i'm merging this now.
