### ISSUE TITLE
Prefix sent packets with a fixed byte sequence

### ISSUE THREAD

**Issue by mickybadia** [hbeni/fgcom-mumble#35]
This is about the UDP packets that you send. All of your recipient clients will almost certainly be reading them in parallel with traffic packets coming from the FGMS network relay, and presumably on the same socket. These traffic packets all start with a "magic" byte sequence "FGFS" which is useful for separating them in their own queue.
I recommend that you also prefix all of your packets in a way that identifies your service, for cleaner operation on the client side. It will avoid assuming that everything unidentified or junk is from you, and allows for yet more services to be added cleanly.

For example, start all of your packets with "FGCom" on a first line (prettier on its own line since you do multi-line plain text). The equivalent byte sequence if you need it is, in hex: `46 47 43 6f 6d`, plus `0a` for a new line.

**Comment by hbeni** [comment]
Currently we have `RDF:`, so i think this should be changed to `FGCOM_RDF\n`, then followed by the actual RDF data?

**Comment by mickybadia** [comment]
You may be sending other things in the future, who knows, and you don't want to be claiming too many byte sequences here. So I would keep "RDF:" as a line header (on every line), and only add a generic line at the top. This way other types of info can later be added by you (introducing new _line_ headers) without forcing client implementations to sort new _packet_ headers while distributing their incoming datagrams.

**Comment by hbeni** [comment]
So you mean something like this, per packet:
```
FGCOM
RDF:<rdf data>
RDF:<rdf data>
...
```

**Comment by mickybadia** [comment]
For exemple yes, which leaves you the possibility of:
* defining new line headers for different types of data
* using the remainder of the first line for version info or whatever, so
long as you keep a few bytes fixed at the very start

>

**Comment by hbeni** [comment]
Real output from my test just now:
```
FGCom: [DBG] [RDF] client sending msg for iid=0 to port=5000: 'FGCOM
RDF:CS_TX=TEST,FRQ=118.700,DIR=231.059158,VRT=0.599233,QLY=0.999958
'
```
Is this OK so far? Note the Newline that termeinates the data line after the QLY field.

I just had one RDF signal in the testcase, but more would follow in the style of the first signal (eg `<data>\n`); so basily like this:
```
FGCOM
RDF:CS_TX=TEST1,FRQ=118.700,DIR=221.059158,VRT=0.599233,QLY=0.999958
RDF:CS_TX=TEST2,FRQ=118.700,DIR=211.059158,VRT=0.589233,QLY=0.989958
RDF:CS_TX=TEST3,FRQ=118.700,DIR=201.059158,VRT=0.57233,QLY=0.979958
RDF:CS_TX=TEST4,FRQ=118.700,DIR=191.059158,VRT=0.569233,QLY=0.969958
```

And the next cycle would repeat that data, including the "FGCOM" header.

**Comment by hbeni** [comment]
now version information is included:
```
FGCOM v0.3.0
RDF:CS_TX=TEST,FRQ=118.700,DIR=90.000000,VRT=0.000000,QLY=1.000000
```

**Comment by mickybadia** [comment]
This is good. I will update my reading code to account for this, but the current one should work nevertheless.
