### ISSUE TITLE
Add MSFS 2020 (SimConnect) compatibility

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#45]
When the new SDK is released, we could (easily?) add support for MSFS 2020.
What is needed is just an interface that takes the simulators plane position and radio configuration and generate UDP packets to the mumble plugin (as per [specification](../tree/master/client/plugin.spec.md)).

A quick google said, that *maybe* msfs2020 is compatible to SimConnect.

That said, it's still open if this compatibility could be reached by this project here, or if it better would be a separate project by its own.
I do not own MSFS2020 so probably will never be able to implement this (Help wanted!)

----
**Useful ressources:**
- https://www.fsdeveloper.com/forum/forums/simconnect.60/ simconnect forum fsdveloper
- P3D location variables: http://www.prepar3d.com/SDKv3/LearningCenter/utilities/variables/simulation_variables.html#Aircraft%20Position%20And%20Speed%20Variables
- P3D avionics variables: http://www.prepar3d.com/SDKv3/LearningCenter/utilities/variables/simulation_variables.html#Aircraft%20Avionics%20Variables
- P3D general systems variables: http://www.prepar3d.com/SDKv3/LearningCenter/utilities/variables/simulation_variables.html#Aircraft%20Miscellaneous%20Systems%20Variables
  (for elec system?)

**It looks like we need:**
|Field|Comment|
|-----|-------------|
|`ATC ID` | is this the multiplayer Callsign?|
|`PLANE LATITUDE` | lat|
|`PLANE LONGITUDE` | lon|
|`PLANE ALT ABOVE GROUND` | altitude AGL|
|`COM ACTIVE FREQUENCY:1` / `COM ACTIVE FREQUENCY:2`| to get the active frequency |
|`COM TRANSMIT:1` / `COM TRANSMIT:2` | is this the PTT state? |
|`COM STATUS:1` / `COM STATUS:2` | to get the COMs status: Radio status flag : -1 =Invalid, 0 = OK, 1 = Does not exist, 2 = No electricity, 3 = Failed (i.E. we could map `0` to `COM_PWR=1` and everything else to `COM_PWR=0` and leave the serviceable etc at default, which should handle all cases "powered/failed/not-present")|

**Comment by tigert** [comment]
FS2020 uses simconnect, though it is not completely implemented yet. But I think it is complete enough for this purpose.

**Comment by hbeni** [comment]
OK, then what i found out is, that probably someone needs to make a small bridge application that uses SimConnect to read out the needed values and converts it to FGCom-mumble UDP protocol messages.

That should be simple, yet i lack the development and testing platform for that, so someone else has to step in here unfortunately....

**Comment by hbeni** [comment]
There is a java library for simconnect: https://github.com/mharj/jsimconnect

1. I think a nice way to go would maybe an integraton into the RadioGUI, where the GUI slaves itself to a SimConnect connection and adjusts the internal data as like the user clicked it together (so we can see visually in the GUI what data SimConnect had read out).
Other than that the RadioGUI could stay the same, especially the bridging to the fgcom UDP protocol would be automatic.
2. Alternatively we could just provide a small java bridge application that just handles the Simconnect connection/readout and the translation to fgcom-UDP packets (which could reuse the already coded client).

----

@mharj: you don't happen to have code already to continuously read out the following properties via Simconnect:
- callsign
- position:
  - latitude
  - longitude
  - height
- radio stack:
  - tuned frequency (at least COM1, but all other COMs of the plane would be good too)
  - PTT state (optional, we could also use a mumble hotkey for that)
  - (optional) operational properties like if its turned on, has power, volume setting, failure-state, tx-power
Maybe you have time to code up a starting point for me, that i can integrate into my project?

**Comment by hbeni** [comment]
I made a new experimental branch. No idea if it works, tough: [`simConnectSupport`](https://github.com/hbeni/fgcom-mumble/tree/simConnectSupport)

**Comment by mharj** [comment]
@hbeni I don't have any examples atm for those (but I remember that position was relatively easy to read).
Code itself is just original copy from lc0277 site with permission, so it's easier to work/clone in github.

**Comment by hbeni** [comment]
@mharj Thanks Marko, for the response!
I coded up some test code yesterday. I am very unsure if i did it right, but at least it's a start to test.

Do you have MSFS2020 and want to give it a shot?
(just run the jar, open the RadioGUI menu option, slave it to SimConnect and see if the values are synced with MSFS?)

**Comment by hbeni** [comment]
And it might very well be, that i need to read in a loop - is this correct?

I think this might be just a one-shot read attempt?
https://github.com/hbeni/fgcom-mumble/blob/423bdc9f487e6f53c8a8e699b46f03a9ca9ae162/client/radioGUI/src/main/java/hbeni/fgcom_mumble/SimConnectBridge.java#L104-L112

**Comment by hbeni** [comment]
Added a new test: [FGCom-mumble-radioGUI-0.9.0-jar-with-dependencies.jar.zip](https://github.com/hbeni/fgcom-mumble/files/5963783/FGCom-mumble-radioGUI-0.9.0-jar-with-dependencies.jar.zip)
It requests data in a 100ms loop now (i hope)

**Comment by hbeni** [comment]
Added a new test: [FGCom-mumble-radioGUI-0.10.0-jar-with-dependencies.jar.zip](https://github.com/hbeni/fgcom-mumble/files/6009043/FGCom-mumble-radioGUI-0.10.0-jar-with-dependencies.jar.zip)
It adds Config options to define the SimConnect connection parameters
