### ISSUE TITLE
Bug: recorder-bot sometimes doesn't release recording state

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#70]
**Describe the bug**
When tuning `910` and talking with PTT, the recording starts.
Once releasing PTT the recorder still is in recording mode and never releases (not even with timeout).

**Expected behavior**
When releasing PTT the recorder should stop recording. Replay should start.

**Logfiles**
None produced yet (should probably be in the recorder bot logfile

**Additional context**
I suspect there is an issue with the lua-mumble modue not reliably detecting the stop-speaking and thus not reliably calling the bot's hook. This should probably be reported to upstream once it is verified.
The recorder bot should however also monitor the change of PTT=on to PTT=off to trigger the end of the recording as a fallback/safeguard.

**Comment by hbeni** [comment]
@bkacjios Hi, how is the sto-speaking callback triggered? Is there special mumble protocol fields, or is that detected by lua-mumble?

**Comment by bkacjios** [comment]
[This is the area of code that detects if the user is speaking.](https://github.com/bkacjios/lua-mumble/blob/855048c653926339a8a7ed611512b9d0bcfb2b25/packet.c#L179)

This if/else statement is where it checks if the user is speaking or not. Essentially, it's checking the audio packet header for the "end of stream" bit that gets set. For speex and celt, this is at 0x80. For opus, this is at 0x2000.

This lines up with the mumbles protocol specification as outlined here.
* [Speex/Celt](https://mumble-protocol.readthedocs.io/en/latest/voice_data.html#speex-and-celt-audio-frames)
* [Opus](https://mumble-protocol.readthedocs.io/en/latest/voice_data.html#opus-audio-frames)

**Comment by hbeni** [comment]
Thank you for the information!

**Comment by bkacjios** [comment]
Actually, after rereading the specification, I think I handle speex/celt backwards. Apparently the 0x80 bit is always 1 until the end of the stream, so basically, it should be 1 when speaking. Could this be your issue? Are you using speex/celt voice data at all? The thing is though I don't think mumble uses speex/celt anymore, so I have no way of testing it right now.

**Comment by hbeni** [comment]
No, i think i'm using Opus, as thats standard since some versions.
I don't think this is causing the problem, as the bots worked fine until recent changes to the client (dev version).

I will dig into that and try to find the cause, but currently i don't think lua-mumble is to blame here :)

**Comment by hbeni** [comment]
This may potentially be related to the recently fixed issue #76. We redid the locking of the PTT handling, and that is whats sometimes missing here...

**Comment by hbeni** [comment]
This may also be a problem caused by the bot manager by broken fifo.... Needs more testing on the server side.

It seems trigger when one releases PTT while still speaking.

**Comment by hbeni** [comment]
@mill-j does the echo-test and recording work reliably for you?

**Comment by mill-j** [comment]
So far, it appears to work reliable. I did notice something that I'm not sure is intended. If I tune RadioGUI com1 to 910 and com2 to another freq such as 123.00, transmitting on com2 will echo as well. The same is true for the RECORD bot.  Is this working as intended?

**Comment by hbeni** [comment]
No, it sounds like a bug...

**Comment by hbeni** [comment]
> > So far, it appears to work reliable. I did notice something that I'm not sure is intended. If I tune RadioGUI com1 to 910 and com2 to another freq such as 123.00, transmitting on com2 will echo as well. The same is true for the RECORD bot. Is this working as intended?

> No, it sounds like a bug...

Fixed in #79

**Comment by hbeni** [comment]
After fixing #79 i was not able to reproduce this here. So maybe it indeed was related, because plain speaking and tuned on a recording frequency was enough to trigger the recording mode. PTT is now correctly evaluated, so the mode triggers/exists correctly.

Let's test a little more before closing this.
[`mumble://fgcom.hallinger.org/fgcom-mumble`](mumble://fgcom.hallinger.org/fgcom-mumble) already has the current code, so can be tested online.

**Comment by hbeni** [comment]
Not reproducible :)
