### ISSUE TITLE
Implement plugin output to support RDF

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#8]
When receiving radio signals, the radio_model should calculate the direction.
- [x] This information should be made available to flightgear (and other clients) via UDP interface so RDF is possible.

- [x] The data format needs to be designed yet, but already identified is:
  - direction
  - vertical angle
  - signal stength
  - callsign
  - frequency

- [x] Introduce a new COM-bound field at the UDP inbound server, so clients can request RDF-data for each radio. Default to `off` This reduces network spam.

**Comment by hbeni** [comment]
The UDP packets need to be sent out at a sufficient high rate (10Hz?), so attached clients can detect when the transmission starts and ends.

**Comment by hbeni** [comment]
`RDF_61-0_CALLSIGN=EDDMobs,RDF_61-0_DIR=180.000000,RDF_61-0_VRT=-5.230091,RDF_61-0_QLY=0.990075`

:) just spawned from "`CALLSIGN=TEST1,LAT=48.303027,LON=11.782159,ALT=4444,COM1_FRQ=123.125`" (north of EDDM, and transmission received from an ATIS bot)

**Comment by mickybadia** [comment]
Hi,
Thanks a lot for implementing this. As far as I can tell it provides everything that is needed for a great simulation of RDF, and completes the set of features we could hope for to improve on the previous generation of FGCom.

The only comment I have is about the IPC scheme: it is a bad idea to hard code the feedback port number (19991). The UDP packets you send should go to the INET address from which you received the original radio packets.

**Comment by mickybadia** [comment]
Question: is "DIR" the radial on which the ACFT is detected or the bearing from the ACFT to the RDF station?

**Comment by mickybadia** [comment]
One more thing: given that you already do all of the direction+quality digest, callsign is currently not completely necessary, but I admit it is still appreciated for possible future use as it is the only way to relate to the UDP packets coming from the FGMS server.
More seriously, why are frequencies not in the data? They seem rather important... It could be just the spec that is missing a ..._FRQ line, but your example line above does not mention it.

**Comment by hbeni** [comment]
Thanks for looking into this :)

> The only comment I have is about the IPC scheme: it is a bad idea to hard code the feedback port number (19991). The UDP packets you send should go to the INET address from which you received the original radio packets.

This was on purpose: i want to restrict this comms to localhost only for security reasons (the mumble client and ATC client/flightsim are assumed to run on the same host anyway).
Currently the mumble plugin framework still lacks user configuration means, so we need to stay on the hardcoded port until this is resolved. It is already on mumble's list.


> Question: is "DIR" the radial on which the ACFT is detected or the bearing from the ACFT to the RDF station? and I suppose this is a true value (not magnetic), correct?

It is the true direction to the source of the radio signal, so always the direction from your position to the signal (if sender is due south, it would be `180`).


> More seriously, why are frequencies not in the data? They seem rather important... It could be just the spec that is missing a ..._FRQ line, but your example line above does not mention it.

That was not implemented yet, didn't had it on the radar. But this is trivially to add.

**Comment by hbeni** [comment]
Frequency added in b42f4d7:
`RDF_15-0_CALLSIGN=EDDMobs,RDF_15-0_FRQ=123.125,RDF_15-0_DIR=180.000000,RDF_15-0_VRT=-5.230091,RDF_15-0_QLY=0.990075`

**Comment by hbeni** [comment]
Btw, im not sure if this is stable already:
-  i want to make sure, fgfs can eat this data too. Im not yet convinced, that the data is in the proper form for that
- it could be that i need to write some terminating line at the end of the RDF signal, so fgfs can pick up that it ended. Maybe you drop in code into ATC-Pie that will ignore (or even handle) the terminator.
(I really do think,that  setting `QLY` to `0.0` is enough for that!)

**Comment by hbeni** [comment]
Hm, would it be good if each own radio had an rdf setting, and just such radios eould be considered for output?

Currently we also generate rdf data for any transmission for any matched radio - would it be better to switch this to „our radio“ and just output the strongest signal? This would result in having just one set of rdf fields for each own radio (COM1=RDF1 then)

**Comment by hbeni** [comment]
OK, i investigated the generic protocol for flightgear.
This can only read fixed position fields, so something dynamic like this here needs a (nasal) parser.

- a) if we don't change this, the goal would be to let fgfs just read the entire string every 1/10 second and write it to the property tree. there, a nasal script can install a listener on that property to detect changes (so the nasal code just runs when the data has changed). The string then needs to be parsed and internal properties changed. I don't know yet if this really makes sense, since most aircraft ADFs (at least Bendix KR-87) can't tune to the VHF radio frequencies anyway (but just navaids/NDBs).
- b) if we change this to a fixed relationship to COM1,COM2,... we could easily map that to flighgear internal properties.

I am very interested on your opinion, but would strongly argue for a):
- No harm is done to fgfs, its just a little more work (and i know nasal rather good).
- We remain the matrix information. This enables us to simulate multi-frequency/multi-receiver RDF devices on airports.

**Comment by mickybadia** [comment]
> > it is a bad idea to hard code the feedback port number (19991). The UDP packets you send should go to the INET address from which you received the original radio packets.
> 
> This was on purpose: i want to restrict this comms to localhost only for security reasons (the mumble client and ATC client/flightsim are assumed to run on the same host anyway).

Even if you want to restrict host, could you not do so without restricting port number? I don't see how a fixed number is better than one already known to be bound with no error on the other party's side. Not to mention that it might not be available at all.

> Currently the mumble plugin framework still lacks user configuration means, so we need to stay on the hardcoded port until this is resolved. It is already on mumble's list.

This is not about user config. In UDP, when you receive a datagram, you also discover who sent it, namely through a host and a port. You could copy that port number for sending, even if localhost is forced.


> > Question: is "DIR" the radial on which the ACFT is detected or the bearing from the ACFT to the RDF station? and I suppose this is a true value (not magnetic), correct?
> 
> It is the true direction to the source of the radio signal, so always the direction from your position to the signal (if sender is due south, it would be `180`).

OK thanks for clarifying. So I recommend you change the spec: "Relative bearing of the signal". Main reason is: "bearing" in aviation means "heading to fixed point/beacon", so more or less the opposite of what your answer here indicates (and why "relative"?)

**Comment by mickybadia** [comment]
> Hm, would it be good if each own radio had an rdf setting, and just such radios eould be considered for output?
> 
> Currently we also generate rdf data for any transmission for any matched radio - would it be better to switch this to „our radio“ and just output the strongest signal? This would result in having just one set of rdf fields for each own radio (COM1=RDF1 then)

I personally think the current implementation is better. RDF is a different piece of hardware from radio receivers/transmitters. It does not technically have to be tuned to the same frequency as the the radios (although ATC-pie does force it that way, but that is just an interface choice).

**Comment by hbeni** [comment]
> I personally think the current implementation is better.

Ok, then we will leave it as-is. A good way to register an RDF-only currently is to register a new invisible radio with the frequency to monitor and set its `VOL=0`.

**Comment by mickybadia** [comment]
> > I personally think the current implementation is better.
> 
> Ok, then we will leave it as-is. A good way to register an RDF-only currently is to register a new invisible radio with the frequency to monitor and set its `VOL=0`.

True. Looks like a hack more than a simulation, but in the end a reasonable limitation in practice so your choice. And you would default RDF to 0 to reduce sent packets. Makes sense.
Also see my EDIT to my last comment.

**Comment by hbeni** [comment]
>> Currently the mumble plugin framework still lacks user configuration means, so we need to stay on the hardcoded port until this is resolved. It is already on mumble's list.
>
> This is not about user config. In UDP, when you receive a datagram, you also discover who sent it, namely through a host and a port. You could copy that port number for sending, even if localhost is forced.

While yopur idea is a good one, i personally don't think that using the sending port of the attached client is a good thing to automatically do. I really think this should be user defineable for the following reasons:
- Order of binding is not known; more specifically, UDP inbound and outbound services are startet at plugin init time, so are already established when the first inbound packages arrive.
- UDP inbound is a separate animal then UDP outbound. They are two completely separate interfaces. Combining them forces a single client at the other end. I want it to be configurable, however, so one can choose freely on which ports the plugin should listen and to which port to connect itself for sending.
- The RDF interface is a server/client application (where the mumble-plugin is the client). Common software let the client configure where to connect to, and the server to configure the listen-port.

This all is just a lottle arkward because currently the user has no means to configure the UDP inbound listenport as well as the port to connect the RDF to.

**Comment by hbeni** [comment]
> EDIT (added): If the point is to reduce the load, what I had proposed---although perhaps in private---is for clients to request RDF explicitly, and why not on certain freqs only.
Thanks, so this leaves me with another todo here :)

**Comment by mickybadia** [comment]
Reading your 23:09 CEST answer I am wondering if there was some sort of confusion, which I would like to dissipate.

I do understand that your FGCom service (listening on port 16661 unless incremented by your script at start-up) is not configurable by the user running the Mumble plug-in. But once the socket, say `S`, is created and bound, it should then be read on and sent from for everything in the lifetime of the service, without the need for any new socket on your side.
Now whatever packet you receive when reading on `S`, you receive from a client address containing a port number, say `N`.
Why not send the RDF packets like this: `S.sendto('localhost', N)`?


> While yopur idea is a good one, i personally don't think that using the sending port of the attached client is a good thing to automatically do.

To be honest it is not really my idea. It is the way that every standard two-way UDP communication that I have seen was implemented, because it neither makes sense for a client to bind two sockets to speak to one service, nor for a server to assume that a client will be able to bind any of its port number choices on her side for sure.

**Comment by hbeni** [comment]
> Why not send the RDF packets like this: S.sendto('localhost', N)?

For two reasons:
 1. using the same socket would enforce the plugin code to share the socket. Thats nothing i want, because the receiving and sending happens in separate threads, running at different rates. Especially the reading would block my socket if clients do not send anything.
 2. It assumes that the RDF data is to be consumed by the same client that sended the configuration data. I do not want to enforce that. RDF is not a kind of "answer" to the plugindata update, it's not tightly coupled, and it should be able to be send to a different process on the machine.

**Comment by hbeni** [comment]
> So I recommend you change the spec: "Relative bearing of the signal".

I enhanced this and i hope its more clear now:
![grafik](https://user-images.githubusercontent.com/13608602/87129283-588e7900-c291-11ea-8cb3-bdb05deefa2c.png)

**Comment by mickybadia** [comment]
Hmm. Please do not worry about me making this personal, it is not. In the end we will all have little choice but to follow your design, and that I am OK with that. I am really only trying to help this find the best design so that we collectively propose the best experience for the community.

In this case I think there some misapprehension of how sockets work, so whether or not you reconsider in the end, I will answer further because to me both of your statements above are wrong.

>     1. using the same socket would enforce the plugin code to share the socket. Thats nothing i want, because the receiving and sending happens in separate threads, running at different rates. Especially the reading would block my socket if clients do not send anything.

Stimmt nicht, sockets do not block as you describe. What blocks is the **thread** that reads on it (if no data is available), **not** the socket itself, which remains available to all other threads. In virtually every program using UDP in the world, the point of threading the reading is precisely not to block the rest of the activity on the socket and to allow use of the same socket for sending.


>     2. It assumes that the RDF data is to be consumed by the same client that sended the configuration data. I do not want to enforce that. RDF is not a kind of "answer" to the plugindata update, it's not tightly coupled, and it should be able to be send to a different process on the machine.
>        In other words: This is no "two way communication", but two independent "one way communication" channels.

I don't see much logic in that, especially as it is inconsistent with what we agreed on above, namely the clients' **requesting** the RDF packets, either through  `RDF=1` or `REQUEST_RDF=freq_list`.

**Comment by hbeni** [comment]
No, i don't treat it personal :smile: 
I appreciate the polite and constuctive conversation here.

> I don't see much logic in that, especially as it is inconsistent with what we agreed on above, namely the clients' requesting the RDF packets, either through RDF=1 or REQUEST_RDF=freq_list.

The RDF-Request is to be made on the UDP input port 16661.

I made an edit to my list above, and i think i cannot solve this, but maybe you have a better idea:
> 3. [EDIT] I have another point (which is the killer argument ): To hook this up to flightgear, one must know the port in advance (fgfs generoc protocol interface). There is no way to have this dynamic.

**Comment by mickybadia** [comment]
> The RDF-Request is to be made on the UDP input port 16661.

Yes, like everything else. What I meant is that if someone requests, then what is sent back has to be considered as an answer. Therefore, it is a two-way comm in IPC terms.

**Comment by hbeni** [comment]
> What I meant is that if someone requests, then what is sent back has to be considered as an answer. Therefore, it is a two-way comm in IPC terms. 

We agree on that. We disagree in the definition of "answer", however:
- as "answer" i would see some message related to the "question".
- This is not the case here: The output is not related in this sense to the input. An ACK message would be however, and that surely should be sended back on the same connection. We do not ACK anything currently, however - there is no "answer" to the UDP requests you sent to 16661.

**Comment by hbeni** [comment]
Commit bd55cf6 just pushed, it implements the specification given above :smile:

**Comment by hbeni** [comment]
An idea just struck my mind, and i added it to #23 : we could have an additional option to make the udp client use the provided port.


Besides that i think the branch is ready for final Testing; i happily help with this when you push to your atc-pie branch .

**Comment by hbeni** [comment]
Good eveneing @mickybadia,
are you preparing something for testing the RDF stuff in its current form, or should i just merge this for now?

**Comment by mickybadia** [comment]
I am, but it needed an entire redesign of my previous RDF system.
And now I am leaving for two days. But you should see some progress come
later in the week.

**Comment by hbeni** [comment]
Ah okay, thanks for the info.
I am standby for now and will push this, once it is settled and tested.

Don't rush! We have the time.

**Comment by mickybadia** [comment]
OK I should have a version _almost_ working but I am afraid that the port thing in fact turns into serious pain for ATCs clients on the same host.
Many users indeed start more than one ATC-pie instance to control or monitor multiple airports, or have a separate CTR window connected between airport hops, and presumably soon each with its own radio set-up. This generates more than one stream of FGCom-Mumble control packets in parallel, and your replying to all of them on a single fixed port makes it impossible for the RDF requesters to receive the respective RDF data.
Could you not at least allow an "RDF to port" option in the control packets, defaulting to 19991 if you want, so that ATC-pie can work with you?

**Comment by hbeni** [comment]
Thank you for that suggestion.
That would be an easy to implement option.
I also had the idea to make a config file for that (as long as mumble has no config Interface), but that would obviously be bound to all fgcom instances.

I will soon start this ok?

**Comment by mickybadia** [comment]
Or you default to 19991 like you wanted, but it also makes sense to consider that any client NOT sending an RDF port is simply not interested in the data.
Mind that a client can change its settings on my side to switch off RDF capability at a location, so you might like to allow for stopping your sending (e.g. "RDF_PORT=0").

**Comment by hbeni** [comment]
Good addition!

Multiple airports will need multiple mumble/plugin instances, there is just single location support.
But i think that was obvious to you already. I think i add it to the readme however.

**Comment by mickybadia** [comment]
> Multiple airports will need multiple mumble/plugin instances, there is just single location support.

Huh? Now I am confused. The whole point being to have a realistic dispatching of messages depending on signal power simulated based on client coordinates, what do you mean by single location here? Why could two ATC clients not send their packets to the same Mumble instance, like multiple pilots would? Of course, they would have different callsigns, and request RDF data to their respective (and different) ports, but what else?

**Comment by mickybadia** [comment]
OK I have deleted a comment because I am still a bit confused but don't want to confuse the thread. I will give it more thought but things are unclear to me at this point why we would really need multiple instances of Mumble for multiple clients (pilots or ATC) while on the same machine. Every client speaker sends his PTT=1 and CALLSIGN=... on transmission; is that not enough for the Mumble client to identify her if needed?

**Comment by hbeni** [comment]
Say, if you have two atc pie clients, you need to also run two mumble instances to connect to with different udp ports.

It would be ***alot*** if work to change that, but its not impossible if course. However i would rather leave that to a future version...

**Comment by hbeni** [comment]
@mickybadia : spec is here, like you suggested. Code is nearly ready too, just needs final testing.
So in short:
- Set `COM1_RDF=1` to signal RDF collection capability of that device
- Set `RDF_PORT=19991` to let the plugin push the info to that port.
  - Port can be switched at runtime.
  - Once you are not interested anymore, transmit `RDF_PORT=0` to disable output completely.

OK this way?

![grafik](https://user-images.githubusercontent.com/13608602/87767576-2645c400-c81b-11ea-8dfa-3995e8207f9f.png)

**Comment by mickybadia** [comment]
OK I have pushed a first version. I must catch a train now but you might get a chance to test it before I do.

Side question: does _PBT affect _RDF for a given COM entry? It would be good if it did not, as you said they are different systems. If it must then I have to trick you with a _PBT=1,_VOL=0,_RDF=1, but I think it would be cleaner to just allow _PBT=0,_RDF=1.

**Comment by hbeni** [comment]
> does _PBT affect _RDF for a given COM entry? 
Currently yes, it does: pbt is intendet to model „switched on“, so a switched off rdf would be expected to be nonfunctional.
I think VOL=0 is the correct way as the rdf receives radio signals but don’t output anything audible.

**Comment by hbeni** [comment]
OK, i tested and it looks good so far: The plugin (the one linked to the ATC-Pie instance) was successfully configured to push out data at port 5000. Then i did a radio transmission from a plugin and the ATC-Pie-linked plugin told me in the log that it produced UDP output to port 5000.

I cklicked around in ATC-Pie, however i was unable to display the RDF data. What do i need to do to see that?

**Comment by mickybadia** [comment]
Hey, thanks. Still away from home home for a few days, but I see you are ahead testing this :-)
For RDF feedback in ATC-pie, first check that an "RDF - - - / - - -" field is visible in the status bar, otherwise turn it on in the location settings. Then, you should see the picked up signals in the first half of the label (radial heading), the second being a memory of the latest bearing (QDM). You can also toggle a graphical display of the signals on radar screens by switching the "RDF line" in the "opts" menu underneath.
Of course for all this, the corresponding frequency must be monitored by the RDF system, i.e. the "RDF" box ticked next to a tuned radio box.

**Comment by hbeni** [comment]
Like this? :grin: 

![grafik](https://user-images.githubusercontent.com/13608602/87857290-dbfd3980-c925-11ea-86e3-7e7f007630d7.png)

**Comment by hbeni** [comment]
@mickybadia: btw, you may have noticed the new `AUDIO_FX_RADIO` config setting https://github.com/hbeni/fgcom-mumble/blob/rdfSupport/client/plugin.spec.md#configuration-options
You may add that as box to the configuration option in the "*System Settings / FGCom radio*" for the plugin.
Default should be "1" (box ticket). if set to 0, radio effects like static will be not applied, helping people that are hearing impaired (I picket that up from an old wishlist item for legacy FGCom somewhere).

**Comment by mickybadia** [comment]
> Like this? grin
Great! Good to see this working without even having tested it myself yet lol.
Also, the line should be fading as the signal quality decreases.

> Heading seems a little off, tough.
For sure displayed QDM should be magnetic, and I know I am interpreting the values you send correctly as true headings. If there is a problem with the graphics it could just be with the position of the line end or something like that. Do you mean to say that the signal painted in your screenshot was supposed to come from the aircraft visible just North-West of the tower?

**Comment by mickybadia** [comment]
> `AUDIO_FX_RADIO`  [...] if set to 0, radio effects like static will be not applied

Good feature and suggestion, I will add this in easily. Should I assume these effects are never applied to the ATIS and echo test inputs?

**Comment by hbeni** [comment]
> Do you mean to say that the signal painted in your screenshot was supposed to come from the aircraft visible just North-West of the tower?

Yes, but the airplane was positioned exactly at the start of the runway (compare it to the position reported from the status page)

> Should I assume these effects are never applied to the ATIS and echo test inputs?

In fact every received radio transmission will have no static 😉

**Comment by hbeni** [comment]
Oh and to clarify: audio effects are solely calculated and applied at the receiving side. The sending audio stream is untouched.

**Comment by mickybadia** [comment]
I have pushed a few corrections and added the FX option today. Now just to understand your screenshot before looking into the positioning problem: you say your ACFT was at RWY 08L threshold and at true 326°, but the radar is displaying it at a PKG spot near TWY W1, which is about true 302°, and the RWY THR is about true 308°. Neither position yields a 326 heading, moreover the painted RDF line you captured seems to correctly align with a true 326.
So at this point I don't think there is much of a problem on my side, but I will try to confirm this once back home. See if you can confirm your heading values in the mean time... Tip if you need to measure headings from the tower (used as RDF and radar centre when unique): a quick right click and drag on an ATC-pie radar scope will give you a magnetic heading, the declination applied being constant and shown in the environment info dialog.

**Comment by hbeni** [comment]
Thank you!
I did check cardinal directions and it seems to only be off by a bit on the western side. Probably i'm mislead a bit? Maybe the radar screen Airport is not the same as the underlying OpenStreetmap card, so it's just my brain which is off?
Numbers do match!

I also looked at the Radio-effects option and had the following idea:
would't it be better to call it "disable radio effects" and have it disabled, so the user has the feel he can "enable" the disable?

**Comment by mickybadia** [comment]
> EDIT: i played around with the test tool and cannot find anything off in the formula to calculate direction, so i strongly think this is just some graphical/interpretation issue on my user desk side.

Mmh, I would not think that as strongly because regardless of the map, a stopped aircraft position and its signal line direction should always match. Your last screenshot indicates an unexplained ~25° difference.

If this difference changes around the compass it is probably a bug in the formula for direction finding. If any use to you, here is my code for self.headingTo(other):
```
lat1 = radians(self.lat)
lat2 = radians(other.lat)
dlon = radians(other.lon - self.lon)
theta = atan2(sin(dlon) * cos(lat2), cos(lat1) * sin(lat2) - sin(lat1) * cos(lat2) * cos(dlon))
```

**Comment by hbeni** [comment]
and [this is mine](https://github.com/hbeni/fgcom-mumble/blob/38269ed60c6f3e4bd5b405e0cf8c66238f6fb821/client/mumble-plugin/lib/radio_model.cpp#L65):
```c
double fgcom_radiowave_getDirection(double lat1, double lon1, double lat2, double lon2) {
    // Implementation taken from: https://www.movable-type.co.uk/scripts/latlong.html
    //                       via: https://stackoverflow.com/a/18738281
    double dLon = (lon2 - lon1);

    double y = sin(dLon) * cos(lat2);
    double x = cos(lat1) * sin(lat2) - sin(lat1)
            * cos(lat2) * cos(dLon);

    double brng = atan2(y, x) * (180.0 / M_PI);
    brng = (int)(brng + 360) % 360;
    brng = 360 - brng; // count degrees counter-clockwise - remove to make clockwise
    if (brng >= 360) brng = 0;

    return brng;
}
```
... so apart from the last three lines, its the same (they are supposed to convert the radians back to compass bearing).

**Comment by hbeni** [comment]
Played a little more with that, and honestly, i have no idea, why it returns those values. :cry:
