### ISSUE TITLE
Bug: Flightgear protocol file not found

### ISSUE THREAD

**Issue by colingeniet** [hbeni/fgcom-mumble#94]
Running `fgfs --addon=[...]/fgcom-mumble/client/fgfs/ --log-level=debug --log-class=io,network`
```
21.61 [INFO]:io         Parse I/O channel request: generic,socket,out,10,localhost,16661,udp,fgcom-mumble
21.61 [INFO]:io           protocol = generic
21.61 [WARN]:network    Couldn't find protocol file for 'fgcom-mumble.xml'
21.61 [ALRT]:io         Failed to parse config=generic,socket,out,10,localhost,16661,udp,fgcom-mumble
21.61 [WARN]:network    add-io-channel: adding channel failed
```
After this, port `16661` is receiving nothing, and of course the mumble plugin doesn't work.

My understanding is that the correct location for the protocol file in order to be loaded from the addon (so without copying it to FGData) is `client/fgfs/FGData/Protocol/fgcom-mumble.xml` (`FGData` added compared to the current path). Moving it to this location fixes the issue.

This is with FG branch next.

**Comment by hbeni** [comment]
Thanks for testing!
I just tested adding the folder to the launcher, and that works here; it yields: `
--addon=/home/beni/Dokumente/FGFS/work/FGCom-mumble/client/fgfs`

![grafik](https://user-images.githubusercontent.com/13608602/112870005-0959d400-90be-11eb-89e6-140033690a74.png)
![grafik](https://user-images.githubusercontent.com/13608602/112870040-14146900-90be-11eb-8b31-b885e4f45246.png)


Does it work if you add it this way?

**Comment by hbeni** [comment]
Sorry, nevermind.
I had an old link dangling here. I can reproduce now.

**Comment by hbeni** [comment]
```
   11.62 [INFO]:io         Parse I/O channel request: generic,socket,out,10,localhost,16661,udp,fgcom-mumble
   11.62 [INFO]:io           protocol = generic
   11.62 [INFO]:network    Reading communication protocol from Path "/home/beni/Dokumente/FGFS/work/FGCom-mumble/client/fgfs/FGData/Protocol/fgcom-mumble.xml"
   11.62 [INFO]:io           medium = socket
   11.62 [INFO]:io           direction = out
   11.62 [INFO]:io           hertz = 10
   11.62 [INFO]:io           name = generic-1
   11.62 [INFO]:io           hostname = localhost
   11.62 [INFO]:io           port = 16661
   11.62 [INFO]:io           style = udp
   11.62 [INFO]:io         add-io-channel: setting name to "fgcom-mumble"
```

looks good now with 0adff82, thanks for spotting and reporting this!

**Comment by hbeni** [comment]
Fixed addon: https://github.com/hbeni/fgcom-mumble/releases/download/v.0.11.1/FlightGear-FGCom-mumble-Addon-0.11.1.zip
