### ISSUE TITLE
Statuspage usage stats limit

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#95]
Make the status bot trim usage stats to a configurable timeframe.

This could probably be easily achieved by:
- open a tmp-file for append
- opening the statsfile for reading
- Read and parse the date string; if its in the timeframe: append to tmp-file
- Append next current line to tmp-file
- Replace stats-file with tmp-file

**Comment by mill-j** [comment]
This sounds like somthing very useful. Curentlt the stats are only useful several days after refreshing the server. After that they get to small to use. I still haven't dug into the server side at all so I probably won't be of much help here.

**Comment by hbeni** [comment]
Thanks for reassuring :)

> I still haven't dug into the server side at all

The server side is basicly just a bunch of LUA-bots listening on the mumble plugin API and parsing messages. They are not neccessary for the plugin to work, but provide additional (optional) enhancements like the statuspage and recording/playback.
Documentation is here: https://github.com/hbeni/fgcom-mumble/blob/master/server/Readme.server.md :)
