### ISSUE TITLE
Bug: mumble transmission mode changes to voice activity.

### ISSUE THREAD

**Issue by colingeniet** [hbeni/fgcom-mumble#97]
I normally have mumble set to PTT. When using the fgcom-mumble plugin, this sometimes get changed to voice activity.

I can reproduce the issue as follows:
1. Start mumble. Ensure PTT mode.
2. Connect to any server. Do _not_ enter an fgcom-mumble channel.
3. Quit mumble.
4. Restart mumble. Transmission has changed to voice activity.

Log: [fgcom-mumble.log](https://github.com/hbeni/fgcom-mumble/files/6329794/fgcom-mumble.log)

This is on the `master` branch for mumble and the plugin.

Looking quickly at `fgcom-mumble.cpp`, there is code to change and restore transmission mode:
```
mumble_transmission_mode_t fgcom_prevTransmissionMode = TM_VOICE_ACTIVATION;

void fgcom_setPluginActive(bool active) {
    [...]
    if (active) {
        [...]
        merr = mumAPI.getLocalUserTransmissionMode(ownPluginID, &fgcom_prevTransmissionMode);
        [...]
    } else {
        [...]
        merr = mumAPI.requestLocalUserTransmissionMode(ownPluginID, fgcom_prevTransmissionMode);
        [...]
    }
```
However, if `fgcom_setPluginActive(false)` is called without a prior call to `fgcom_setPluginActive(true)`, this will just switch to voice activation. I think this is exactly what happens when stopping mumble without actually using fgcom-mumble.

**Comment by hbeni** [comment]
Hi there, thanks for reporting!

Does this solve it for you? https://github.com/hbeni/fgcom-mumble/tree/Issue-97

**Comment by colingeniet** [comment]
Yes it does, thank you!
