### ISSUE TITLE
Windows native build

### ISSUE THREAD

**Issue by dextercai** [hbeni/fgcom-mumble#99]
We should add a github workflow + makefile for building windows binaries natively.
Maybe related to the cmake switch: #82 

_Original text:_

-----
I recently try to build the target on WindowsOS. But it doesnt work.

Did the project have support the building process on windows?

**Comment by hbeni** [comment]
No.
Currently the makefile supports cross-compiling to windows using mingw, and we have windows release binarys as well as nigthlies.

It would be cool, if you could provide a windows compile makefile :)

**Comment by dextercai** [comment]
As a golang programmer, it may be different for me. But I will try.

**Comment by hbeni** [comment]
Cool! I have no idea nor a dev environment on windows.

Does the release binary not work for you?

**Comment by dextercai** [comment]
The release binary (32 bit) works well for me, I tested it just now. 
If this repo can work well on Windows, It may be a great application for simfly player.

**Comment by hbeni** [comment]
Never heard of _simfly player_, tell me more :)

**Comment by dextercai** [comment]
simulation flight player.
It is awesome for the simulation flight to get a radio-style voice experience

**Comment by hbeni** [comment]
Sounds nice, do you have a link to the software?

Bear in mind, that you also need a 1.4.0 mumble server running with a specially named channel (`fgcom_mumble-....`, to have this working.
For testing you can use my test server at fgcom.hallinger.org for now, but this _may_ go out of service once mumble 1.4.0 is released (which will still take quite some time!).

**Comment by mill-j** [comment]
I have a Windows install with a GCC dev enviroment that I can use if needed. If I **get the time**, I _might_ see what I can find in getting it to build natively. So far building stuff from source on windows leaves much to be desired when comparing to Linux. I should also see what the mumble status is for mac, since I do have access to a x86_64 High Sierra install with GCC.

**Comment by hbeni** [comment]
@mill-j Fahim Dalvi has already managed to build it on mac, see here: #100 

What is missing is:
a) getting all this into a github workflow so i can build it too reliably for releases
b) having the neccessary prerequisites in the build workflow so it actually succeeds (openssl, etc; but openssl should already be buildable as we have it as submodule in the repo for the windows cross build)

**Comment by dextercai** [comment]
Good news.
The makefile works well on Windows. Just need use x86_64-w64-mingw32-g++ instead of x86_64-w64-mingw32-g++-posix.

I used cygwin64 with mingw32.
